### ISSUE TITLE
keyszer pegs a CPU

### ISSUE THREAD

**Issue by Lenbok** [joshgoebel/keyszer#106]
**Describe the bug or unexpected behavior**

I just started using keyszer a day or so ago. I noticed that it has started consuming 100% CPU (although it is still mapping keys correctly, so it's not just hung). At this stage I don't know where or what has triggered it, but when I attach an strace it's full of:
```
epoll_wait(6, [{EPOLLERR|EPOLLHUP, {u32=10, u64=10}}], 8, 777) = 1
read(10, 0x7ffd849ad710, 1536)          = -1 ENODEV (No such device)
```

**Sample Config or Instructions to Reproduce**

**Your setup**

- Python version: 3.8.10
- Keyszer version: bfc2505 (pr #105)
- Kinto version (if applicable):
- Devices `(+K)` we're handling input from:

I am running with `--watch`

**Expected behavior**

**Additional context**

**Comment by Lenbok** [comment]
Update: This occurs whenever I unplug my keyboard, and is independent of whether I use `--watch`.

**Comment by RedBearAK** [comment]
@Lenbok 

It's something about the device not being properly removed from the device registry. I was seeing the same thing when disconnecting an external USB keyboard from a laptop. 

I submitted a PR to hide the error in the log, but it doesn't actually cure the problem in the background. It's like it's stuck in a loop looking for the device, but otherwise everything keeps working. I wasn't actually clever enough to find the root of the issue. Maybe you can. 

See issue #82.

**Comment by joshgoebel** [comment]
I'll try to find time to fix this one soon.

**Comment by Nthalk** [comment]
I have a USB switcher, and it looks like this happens 100% of the time when switching away, and never recovers, even on switch back.

**Comment by Nthalk** [comment]
Adding a udev rule for my USB device that restarts keyszer is a workaround. I got my usb attrs via `udevadm monitor` and `udevadm info -ap <THE_MONITOR_INFO_SECTION>`

And this file: /usr/lib/udev/rules.d/99-keyszer-workaround.rules
```
ACTION=="remove" \
  , SUBSYSTEM=="usb" \
  , ATTRS{idProduct}=="0102" \
  , ATTRS{idVendor}=="29ea" \
  , RUN+="/usr/bin/systemctl restart keyszer.service"
```

**Comment by jeffgran-dox** [comment]
> And this file: `/usr/lib/udev/rules.d/99-keyszer-workaround.rules`

I added this rule as well to the same file, to also restart keyszer when I plug the keyboard back in:

```
ACTION=="bind" \
  , SUBSYSTEM=="usb" \
  , ATTRS{idProduct}=="6060" \
  , ATTRS{idVendor}=="feed" \
  , RUN+="/usr/bin/systemctl restart keyszer.service"
```

**Comment by joshgoebel** [comment]
Can anyone test #122

**Comment by RedBearAK** [comment]
> Can anyone test #122

Works for me. Left a comment on the PR.

**Comment by joshgoebel** [comment]
I'm closing this with #122.  If we still have _another_ CPU burn issue we need to open a new issue and we really need some more information/debugging by someone to help identify the source of the increase. (perhaps keep adding logging until we figure out where the CPU is burning?)

**Comment by Nthalk** [comment]
For anyone that has this issue, in addition to the UDEV rule to restart on plugin, there's still a spin lock on getting devices when they are plugged back in.

To address the symptom (my computer heating my home), and not the issue, I've installed `monit` to kick the service when it starts pegging a cpu.

The keyszer monit config looks like this:

```
check process Keyszer  with pidfile /var/run/keyszer.pid
   group services
   start program = "/usr/bin/systemctl start keyszer"
   stop  program = "/usr/bin/systemctl stop keyszer"
   if 5 restarts within 5 cycles then timeout
   if cpu usage > 95% for 5 cycles then restart
   if mem usage > 95% for 5 cycles then restart
```

Of course, I had to modify the systemd service to include writing the keyszer pid:

```
[Unit]
Description=Keymapping service for keyszer

[Service]
Environment='DISPLAY=:1'
User=keymapper
Group=keymapper
ExecStart=/home/keymapper/.local/bin/keyszer -w
Restart=always
Type=simple
RestartSec=10
ExecStartPost=+/bin/sh -c "echo $MAINPID > /var/run/keyszer.pid"

[Install]
WantedBy=graphical.target
```

Anyway, hope this helps someone.

**Comment by joshgoebel** [comment]
>  there's still a spin lock on getting devices when they are unplugged.

If someone could get a trace on where exactly this is happening...  I thought we had fixed this when we rescued `FileNotFoundError` and changed code path for dealing with disconnects.

**Comment by Nthalk** [comment]
> > there's still a spin lock on getting devices when they are unplugged.
> 
> If someone could get a trace on where exactly this is happening... I thought we had fixed this when we rescued `FileNotFoundError` and changed code path for dealing with disconnects.

Is there a patch or a code example of the suspected hotloop where I can dump helpful info to the log?

**Comment by joshgoebel** [comment]
You could look at `device_change` (input) and `devices.py`...
