### ISSUE TITLE
Getting the keymap name from within a "when" conditional? 

### ISSUE THREAD

**Issue by RedBearAK** [joshgoebel/keyszer#107]
I'd like to be able to print out the name of the keymap that calls on a function from within the "when" condition. 

Technically I can get the keymap names to print out every time `matches()` from the `Keymap` class is called, by just hacking in a print command: 

```py
    def matches(self, context):
        print(f"Keymap name: {self.name}")
        return self.conditional is None or self.conditional(context)
```

I'm wondering if there is another way to access the keymap name from within a custom function like my `matchProps()` function, so that it's easier to get this information to print out only when debugging output is enabled in the function, and without needing to modify `keymap.py`.

**Comment by joshgoebel** [comment]
Python is pretty easy to monkey patch so you're probably just want to modify the keymapper class from within your config file, capture the existing function, wrap it in a new function that adds the logging you want. 

I don't know how to do it off the top of my head, but I know it's not difficult.
