### ISSUE TITLE
Importing lists/vars/functions from main config in include files?

### ISSUE THREAD

**Issue by RedBearAK** [joshgoebel/keyszer#108]
Somehow, include files need to be able to reference the main config file, to draw on established definitions of things like lists, variables and functions that only exist within the config file. Right now, when I move things into a separate file and try to view the contents of the include file in VSCode, I end up with quite a few error indicators and "not defined" issues. 

Most can be cured with the usual `from keyszer.config_api import *`, but that's only for things that are built into keyszer itself. 

VSCode is fine with a line like this that references my own config file (keyszer_kinto.py): 

```py
from kinto_keyszer import *
```

That will make the errors go away when viewing or editing the include file. But when I try to actually run the code with that kind of import line, I get a `ModuleNotFoundError` and it won't run. 

```py
ModuleNotFoundError: No module named 'keyszer.kinto_keyszer'
```

With a dot added for a relative reference: 

```py
ModuleNotFoundError: No module named 'kinto_keyszer'
```

I've been trying to find a way to refer to these resources in the main config that will work in VSCode and still run successfully from the command line, but no luck so far. 

Any ideas? 

Well, OK, this seems to work. It gets VSCode to stop complaining about a bunch of things being undefined, and the program will still run since it just bypasses the module error. But it seems a bit excessive to need to do it this way. 

```py
try:
    from .kinto_keyszer import * 
except ModuleNotFoundError:
    pass
```

**Comment by joshgoebel** [comment]
I would turn off linting in VS Code for this, it doesn't know enough about "include" files to understand what it is valid and what isn't.  Code in includes runs in the exact same context as the parent (as if it was all one big file)... anything in scope in the parent should be in scope in the include - but VS Code won't understand that.

**Comment by RedBearAK** [comment]
That is true. VSCode can't easily know what a function like `include()` is going to do at runtime (from within another file) to make the content of an included file "legitimate" as far as Python is concerned. But I don't consider just turning off the linting to be a good solution to that. For those of us still getting familiar with Python, the ability to have an IDE/editor throw a warning when even doing something as simple as leaving out a comma or a closing bracket somewhere, is immensely time-saving. Not to mention all the auto-completion and hover info, and ability (in most cases) to go to where an object is defined. 

Anyway, the solution of using `try` does seem to make it work in both contexts. Although, when I tried to move the include files into a subfolder and use a double dot to get back to the config in the parent folder, Python threw a different error (`ImportError` I think). I don't really understand that one since I've seen dot-dot notation for other imports within `keyszer` working just fine. 

But If I also except that specific error and/or add a `finally` statement the problem should be solved. I was just hoping there might be a simpler way. 

Oh, looks like avoiding using a relative dot or dot-dot syntax avoids the `ImportError`, regardless of whether the included file is in the same folder or a subfolder. That's better. But there must be a way to also get Python to acknowledge the location of the config file as legitimate and stop raising the `ModuleNotFoundError`. I'll keep looking into it. 

```py
# To quiet down linting errors in editors like VSCode
from keyszer.config_api import *
try: from kinto import * 
except ModuleNotFoundError: pass
```

**Comment by joshgoebel** [comment]
Good luck. There might indeed be some way. Your just swimming upstream a little. 😀
