### ISSUE TITLE
error: (EE) Bad display name ""

### ISSUE THREAD

**Issue by anaxonda** [joshgoebel/keyszer#109]
**Describe the bug or unexpected behavior**
Keyszer does not work. Gives error `(EE) Bad display name ""`.

**Sample Config or Instructions to Reproduce**
Running keyzer with this command gives me that error:
`.local/bin/keyszer -c .config/keyszer/config.py`

Error given upon executing keypresses once keyszer is running.

**Your setup**

- Python version: 3.10.7
- Keyszer version: 0.6.92

**Additional context**
I previously had keyszer working, following the instructions to create new user 'keymapper', set up the udev rules and a systemd file. Upon reboot keyszer is not working at all. I disabled the systemd service and tried to run from keymapper user.

Running the described command from keymapper user gives that error. If I run as sudo I get a different error:
```Traceback (most recent call last):
  File "/home/keymapper/.local/bin/keyszer", line 5, in <module>
    from keyszer.cli import main
ModuleNotFoundError: No module named 'keyszer'```

Would appreciate some guidance on how to proceed. Thanks

**Comment by joshgoebel** [comment]
You need to make sure it has access to the active users X session.

**Comment by anaxonda** [comment]
I have run `xhost +SI:localuser:keymapper`. Is this correct?

```
$ xhost
access control enabled, only authorized clients can connect
SI:localuser:keymapper
```


I have the same problem after running it.

**Comment by anaxonda** [comment]
Ok, I found if I run the same keyzer command, but instead of as keymapper user, as local user via `su keymapper -c "/home/keymapper/.local/bin/keyszer -c /home/keymapper/.config/keyszer/config.py"` keyszer works successfully. 

Does it make sense that it would run successfully as local user with `su` but not as keymapper user?

**Comment by joshgoebel** [comment]
Maybe your display variable isn't set correctly?

**Comment by anaxonda** [comment]
That was it. Running `export DISPLAY=:0` fixes the problem.

One more question, keymapper user should not need to be added to sudoers file, correct?

**Comment by joshgoebel** [comment]
It should not.  The user is never intended to become root.
