### ISSUE TITLE
(enh) Auto-generate key definitions from `xmodmap -pke`

### ISSUE THREAD

**Issue by RedBearAK** [joshgoebel/keyszer#114]
@joshgoebel 

Someone on the `evdev` GitHub pointed me to another project called input-remapper that uses the output from `xmodmap -pke` (which changes when you change the keyboard layout) and an integer offset of minus 8 to generate the correct keycodes for the current keyboard layout, rather than relying on a static key definition file. This may be a way to get around the way `keyszer` wants to act like it's always using a US layout, and finally support international keyboards properly. 

https://github.com/sezanzeb/input-remapper/blob/beta/inputremapper/configs/system_mapping.py

I'm just beginning to look at how input-remapper is doing this. Not sure yet if it's constantly updating this system mapping or if it also has some ability to notice when the user changes the keyboard layout and just re-run the code to regenerate the mapping when it needs to. 

And a reference for where the key names originally come from: 

https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h

**Comment by joshgoebel** [comment]
I feel like we'd still have some sort of config language (if we were to support layouts in such a fashion) - the fact that you could build that file potentially from something like `xmodmap -pke` would be something for an extra-library utility to help with - and that might be a cool script indeed. 

I'm not interested in shelling out to other binaries for key functionality though, so I don't see how this could be part of the core package.  Possibly `contrib/scripts` or some such?  If you end up playing around here I'd be curious to see what you come up with.

**Comment by RedBearAK** [comment]
@joshgoebel 

That `xmodmap -pke` command ended up not being as useful as I had hoped. It would spit out the key info for all enabled layouts rather than just the current layout, and did not seem to provide any way of identifying which layout was active. 

The only tool I've found that is able to identify the currently active keyboard layout is this project on GitHub: 

https://github.com/nonpop/xkblayout-state

With the right options this finally shows the active keyboard layout in a useful way: 

```sh
$ echo $(./xkblayout-state print "%s(%e)-%n")
us(us)-English
```

Unfortunately this is once again a third-party binary tool and appears to be written in C or C++, so I have no idea if the technique it uses to identify the keyboard layout could ever be integrated into `keyszer`.
