### ISSUE TITLE
Keep very high CPU usage after remove external usb keyboard but not restart keyszer service.

### ISSUE THREAD

**Issue by zw963** [joshgoebel/keyszer#116]
![image](https://user-images.githubusercontent.com/549126/202893786-04990fd0-9bb4-4add-aa28-5edf3bce2cd2.png)

I start keyszer when i connect my external keyboard, use following command line.

```sh
~/.local/bin/keyszer -c my_config.py
```

after i disconnect it, i forget to restart keyszer service, CPU keep very high usage, with no error log.

i consider there is a dead loop is keep running which cause this issue.

Thanks

**Comment by RedBearAK** [comment]
@zw963 

This is a duplicate of issues #106 and #82. 

> i consider there is a dead loop is keep running which cause this issue.

Yes, something keeps trying to access the missing device after it is physically removed.

**Comment by zw963** [comment]
Okay, close for follow on original issue.
