### ISSUE TITLE
Stuck keys troubleshooting

### ISSUE THREAD

**Issue by RedBearAK** [joshgoebel/keyszer#28]
@joshgoebel 

> f8165f5
> And try tuning the delay (manually) from 1s to lower and see if that helps... tranform line 200 or so... call_later.

Finally got a chance to do a fresh clone and try this. I set it to 0.2 and it seems to work a lot better. If I'm particularly quick it's still not quite fast enough to do what I expect. So I set it to 0.1. 

It's safe to say I'm now confused a bit why the suspension time is even necessary if it can be set to such a short delay. 

And still having issues with stuck modifiers. Seems to happen pretty reliably after using something like Cmd+Tab then moving to Cmd+Shift+Grave. Once the new window pops up, there is definitely at least one stuck modifier. I think it may be multiple keys because tapping just Alt (physical Super/Win) or RC (physical Alt) doesn't completely stop unexpected actions from occurring.

**Comment by joshgoebel** [comment]
> after using something like Cmd+Tab then moving to Cmd+Shift+Grave

I don't know what that means exactly... can you be more specific?  I need very explicit steps if you want me to try to reproduce over here.  And if you might be interested in learning to write some units tests that'd be even better - you could just pass me a failing test in a PR - and then I could make it green... 

> It's safe to say I'm now confused a bit why the suspension time is even necessary if it can be set to such a short delay.

The lower you set it the more likely you are to trigger false key presses... if you set it to 0.1 and then you try to Cmd click but you aren't fast enough the "start menu" pops up on some distros, etc... so setting it too low just brings this problem back.

**Comment by joshgoebel** [comment]
I'm not sure 0 works but theoretically at 0 you should have the EXACT broken 0.4 behavior of pressing keys too soon...  it's not exactly the same of course because I'm using a single delay for multimods since  two different delays doesn't make a lot of sense in my book if they are going to be similar anyways.

**Comment by joshgoebel** [comment]
The great thing about that delay was that (until you found mouse clicking) the delay probably could have been MUCH LONGER... since most people don't press and hold modifiers on their own (and need that to trigger) - the next keys are usually soon to follow and we'll know what to do... so the delay effectively didn't matter... just so long as it wasn't too short.

Of course someone who was quite a slow typist might need a longer delay... but for me 1 second is an eternity to complete a keystroke.

**Comment by joshgoebel** [comment]
>  I think it may be multiple keys 

You don't have to guess, that's why I added the DIAG key to tell you *exactly* what the internal state is.

**Comment by joshgoebel** [comment]
You should try the `exerted` branch.  Has the latest stuck/sticky fixes.

**Comment by RedBearAK** [comment]
Just ran into a complete loss of keyboard input issue. I had remembered to change the debug key to F8 but it didn't work. It's always worked recently, since I changed it from F16. Ended up having to close the terminal tab again. 

I was just in here trying to type another comment in a different thread, tried to copy some text and paste it, and then couldn't type anything or switch windows or anything. 

Will remember the DIAG dump next time. I have that on F7.

**Comment by joshgoebel** [comment]
>  I had remembered to change the debug key to F8 but it didn't work.

Make an issue and suggest an API and we can make those keys definable in your config. :)  Perhaps `diag_key` and `bailout_key` or something...

**Comment by joshgoebel** [comment]
DIAG isn't likely to work if BAIL doesn't work... you'll need the log if you're having that level of issues... I just started running the branch myself... I wasn't yet - but all the tests are green.  We'll see if I find any weird issues.  Nothing so far.

**Comment by RedBearAK** [comment]
No good on the `exerted` branch. Cmd+Tab is broken. No task switcher, no held key behavior. 

```

(DD) WM_CLS 'gnome-text-editor' | DV 'AT Translated Set 2 keyboard' | KMAPS = [GNOME Text Editor, Anonymous keymap, General GUI, Wordwise - not vscode]
(DD)   COMBO: RCtrl-TAB => Alt-TAB [General GUI]
(DD) spent modifiers [<Key.RIGHT_CTRL: 97>]
(DD) resuspending keys
(DD) suspending keys [RCtrl<Key.RIGHT_CTRL>]
(OO) press LEFT_ALT
(OO) press TAB
(OO) release TAB
(OO) release LEFT_ALT

(II) in TAB (release)
(DD) on_key TAB release

(II) in LEFT_ALT (release)
(DD) on_key RIGHT_CTRL release
(DD) silent lift of spent mod RIGHT_CTRL

*** TRANSFORM  ***
are we suspended: False
_suspend_timer:
None
_last_key:
TAB
_states:
{}
_sticky:
{}
*** OUTPUT ***
_pressed_modifier_keys:
set()
_pressed_keys
set()


(II) in F7 (press)
(DD) on_key F7 press
(OO) press F7

(II) in F7 (release)
(DD) on_key F7 release
(OO) release F7
(EE) BAIL: Emergency shutdown requested.
```

**Comment by joshgoebel** [comment]
> - real keys released on output

You didn't modify your config to support it...

And I'm at a loss, the output looks spot on:

```
(OO) press LEFT_ALT
(OO) press TAB
(OO) release TAB
(OO) release LEFT_ALT
```

**Comment by RedBearAK** [comment]
> You didn't modify your config to support it

Oh, I haven't looked at that thread yet. Sounds like that will make my config incompatible with Kinto/xkeysnail already.

**Comment by RedBearAK** [comment]
I did this in a separate `keyszer.py` config file and it seems to be working so far. 

```
    K("Alt-Tab"): pass_through_key,                 # Default - Cmd Tab - App Switching Default
    K("RC-Tab"): [bind, K("Alt-Tab")],                      # Default - Cmd Tab - App Switching Default
    K("RC-Shift-Tab"): [bind, K("Alt-Shift-Tab")],          # Default - Cmd Tab - App Switching Default
    K("RC-Grave"): [bind, K("Alt-Grave")],                  # Default not-xfce4 - Cmd ` - Same App Switching
    K("RC-Shift-Grave"): [bind, K("Alt-Shift-Grave")],      # Default not-xfce4 - Cmd ` - Same App Switching
```

**Comment by RedBearAK** [comment]
Not getting any stuck modifiers so far, even when transitioning from Cmd+Tab to Cmd+Shift+Tab or Cmd+Shift+Grave (while holding Cmd). That's when it would always happen with the other branch. 

But, I'll have to go back in and set the delay down to 0.1 again for the clicking of links. 

> Of course someone who was quite a slow typist might need a longer delay... but for me 1 second is an eternity to complete a keystroke.

Hate to say this, but I have frequently held the Cmd key down for significant periods of time in macOS or Kinto while clicking a selection of links to open in background tabs. Shopping comparisons, opening a bunch of references from google links, things like that. I just keep that key held down for as long as I feel like I'm going to open another link, and it's never been a problem. 

Then again, Kinto kills Unicode character entry by excessively emitting RC presses/releases. So... 🤷🏽

**Comment by joshgoebel** [comment]
You should be able to start tabbing backwards now as well while holding your task switcher open...

**Comment by joshgoebel** [comment]
>  I'll have to go back in and set the delay down to 0.1 again for the clicking of links.

Is 100ms long enough that the key always registers before your first click?

**Comment by RedBearAK** [comment]
I’m not at my computer right now but I would venture to guess that with the necessary coordination between hands or the unusual reorienting of one hand to hold Cmd while tapping or clicking the touchpad, a delay of 100ms will work about 98% of the time.

**Comment by joshgoebel** [comment]
I kind of wish you had some software that would popup and annoy you if you didn't do it fast enough so you could test that side of things too. :)  I wager 100ms isn't long enough for all users to find the second key in a combo and my thinking was for support requests better too long of a delay than too short of one... 

Until the silly clicking issue messed it all up. :)

**Comment by RedBearAK** [comment]
> You should be able to start tabbing backwards now as well while holding your task switcher open...

Yes, starting with the Shift variants did seem to work as expected with this setup. Not just transitioning from starting with the forward variants.

**Comment by joshgoebel** [comment]
@RedBearAK If you're still having good results I'll merge the branch back into main.

**Comment by RedBearAK** [comment]
@joshgoebel 

This afternoon is actually the first time I've been able to get back on the laptop running `keyszer`, but it's been running the whole time since then and was acting fine when I started using the machine. I haven't yet experienced any stuck (or lost) keys that I know of, after doing various typing, app switching and cut/paste type operations. But I haven't been using it for long. 

You'll have to remind me how to get back on the "main" branch (just `git checkout main`?), then I'll need to reapply my "fixes". The config options for the DAIG and DEBUG keys will minimize that. 

Maybe you could add a config option for the `sleep` delay in output. `output_delay_ms` or something like that. Or maybe just an on/off kind of thing, since only the bare minimum 1ms delay seems to be necessary, when it is even necessary at all. Default to off, let the user turn it on if they have issues with macros.

**Comment by joshgoebel** [comment]
> Maybe you could add a config option for the sleep delay in output. 

See the... damn which thread it is... this is coming, but still trying to figure out what to do about all the delays...

**Comment by joshgoebel** [comment]
> git checkout main

Though you may want to `git stash` and `git stash pop` to save and pop your stuff. (unless you commited it, then you might like `cherrypick`.

**Comment by RedBearAK** [comment]
> damn which thread it is... this is coming

Oh, what a tangled web of threads we weave... 👍🏽
