### ISSUE TITLE
What happens if multipurpose modmap is resumed before another key?

### ISSUE THREAD

**Issue by joshgoebel** [joshgoebel/keyszer#37]
After 1 second (or configurable delay) the multi-purpose key will wake up and try to resolve itself... if no other keys have been pressed (and it hasn't been released) then it will resolve as a modifier... but if it happens to be a regular key we can't exert it on the output - of that will just send the key to the output...

So right now this is buggy... I'm beginning to wonder if for non-modifier multi-purpose modifiers (say using `Enter` or `;` as a multi-purposed mod that we shouldn't just suspend indefinitely until a second key is hit (or the first is released).

**Comment by joshgoebel** [comment]
As for the original xkeysnail behavior - it would wait indefinitely because it had no other choice - the only events that could "wake" it were input events from the input devices...

**Comment by joshgoebel** [comment]
@kbreaves

```
define_multipurpose_modmap(
    # {Key.ENTER: [Key.ENTER, Key.RIGHT_CTRL]   # Enter2Cmd
    # {Key.CAPSLOCK: [Key.ESC, Key.RIGHT_CTRL]  # Caps2Esc
    # {Key.LEFT_META: [Key.ESC, Key.RIGHT_CTRL] # Caps2Esc - Chromebook
    {                                         # Placeholder
})
```

What is this section for?  Do you encourage it's use or have knobs in our of your UIs to turn these on and off?

**Comment by joshgoebel** [comment]
@rbreaves

```
define_multipurpose_modmap(
    # {Key.ENTER: [Key.ENTER, Key.RIGHT_CTRL]   # Enter2Cmd
    # {Key.CAPSLOCK: [Key.ESC, Key.RIGHT_CTRL]  # Caps2Esc
    # {Key.LEFT_META: [Key.ESC, Key.RIGHT_CTRL] # Caps2Esc - Chromebook
    {                                         # Placeholder
})
```

What is this section for?  Do you encourage it's use or have knobs in our of your UIs to turn these on and off?

**Comment by joshgoebel** [comment]
> Actually we should just force that the right side of multipurpose modmaps have to be REAL modifiers 

In reading the old code again I think this may have always been the case, so I may end up just closing this issue until someone comes back with actual issues using multi-modmaps.

**Comment by rbreaves** [comment]
> What is this section for? Do you encourage it's use or have knobs in one of your UIs to turn these on and off?

Yes, system try menu, Customize -> Tweaks. Although I do not think I have made Enter2Cmd available to the GUI as either no one requested it or it was requested & it seemed like an esoteric need.. who would assume holding down Enter would turn it into a Cmd key lol?

**Comment by joshgoebel** [comment]
You should definitely test this when you try keyszer... should work but I haven't done much playing with the multi-maps stuff. (and it got a pretty big rewrite)
