### ISSUE TITLE
Name of timeout settings

### ISSUE THREAD

**Issue by joshgoebel** [joshgoebel/keyszer#41]
@redbearak thoughts?

I'm thinking:

- multipurpose
- suspend
- exert_post_combo

And yes we would document these and their uses...

```py
timeouts(
  multipurpose = 1,
  suspend = 0.1,
  exert_post_combo: 0.25
)
```

The old `define_timeout` API would set the multipurpose timeout, as it always has.    The `exert_post_combo` I don't have yet but if I add it later it would prevent false keypresses AFTER a combo by adding a small delay there (to give the user a chance to lift the keys) before the keys were reexerted on the output (currently they are reexerted immediately).  That seems far less risky to me than the `suspend` which is the delay that happens a mod is first held - and what breaks your Cmd-clicking.

**Comment by RedBearAK** [comment]
> exert_post_combo

This sounds like an interesting variation. But I'd need concrete examples of the flow with each of these to really have an opinion on anything. 

> give the user a chance to lift the keys

My mind strays to Option key shortcuts (physical Win/Super, logical Alt). This would help keep those shortcuts from opening menus, if you release within the timeout period?

**Comment by joshgoebel** [comment]
> This would help keep those shortcuts from opening menus, if you release within the timeout period?

Yes, that's what `suspend` does (for initial keydowns) - though I suppose they could also incorrectly retrigger AFTER combos as well without `exert_post_combo`...  I'm not sure why that isn't reported more as I'd think the problem would be the same.

> But I'd need concrete examples 

Pretty sure there are more examples in other threads.  It's all about suspending the keys to try and predict the future.

- `suspend` is just my name for holding back the initial key down
- and `exert_post_combo` is my name for holding back pushing the keys down again after a combo

**Comment by RedBearAK** [comment]
I kind of like the more verbose naming you were using in this thread, and the lack of `exert`: 

https://github.com/joshgoebel/keyszer/issues/9#issuecomment-1156490616

**Comment by joshgoebel** [comment]
This is implemented in main now:

```
timeouts(
    multipurpose = 1,
    suspend = 1,
)
```

**Comment by RedBearAK** [comment]
@joshgoebel 

This seems like an issue that could be closed.
