### ISSUE TITLE
New functions for easier macro strings and Unicode? 

### ISSUE THREAD

**Issue by RedBearAK** [joshgoebel/keyszer#43]
Macros with lengthy strings are a huge pain to implement currently due to the fact that even the simplest of strings needs to be broken down by the user into individual "keystrokes" inside `K` function constructs. Shortcut combos are one thing, but when there is just a regular string it seems like there should be a way to make things a lot easier on the user by offering a function that just takes whole strings, without forcing the user to pre-digest them. A new function (maybe `S` for string) could just take all the literal characters within the quotes and send them one by one to output (through any necessary limiter for output reliability, of course). 

So instead of doing this kind of nonsense: 

```
    K("C-comma"): [
        K("C-T"),K("a"),K("b"),K("o"),K("u"),K("t"),
        K("Shift-SEMICOLON"),K("p"),K("r"),K("e"),K("f"),
        K("e"),K("r"),K("e"),K("n"),K("c"),K("e"),K("s"),K("Enter")
    ],
```

The user could instead just do something like: 

```
    K("C-comma"): [ K("C-t"), S("about:config"), K("Enter") ],
```

I wasn't even really thinking about this while I was drafting this but of course this would make it hugely easier to do the Unicode stuff. 

```
    K("Alt-Key_1"): [
        K("Shift-Ctrl-u"), S("00A1"), K("Enter")
    ],
```

But if I had my preference, before I embark on implementing a couple hundred shortcuts for the Option key special characters I would vastly prefer a dedicated Unicode sending function to encapsulate all that into a simpler form, like... 

```
# Inverted Question Mark
K("Alt-Key_1"): U("U+00A1"),
# Dead Keys: Grave Accent
K("Alt-Grave"): { 
    K("a"): U("U+00E0"),
    K("e"): U("U+00E8"),
}
```

**Comment by joshgoebel** [comment]
I'm not sure why one would prefer:

`U("U+00E0")` vs `U("00E0")`

And of course this isn't entirely trivial... take `S("00A1")`... is that "a" or "A", and there is no "A" key of course, it would be [shift, A], etc..

Same for `S("about:config")`... in order to convert strings to keys you'd need a fairly large map of at least the primary ASCII characters... (and raise an error if you had a character we didn't have a mapping for)

Eventually you could have `US(unicode_string)`, but I'm pretty sure I'm not interested in maintaining a full unicode mapping table inside the keymapper... however a simple ASCII table for allow a `S` helper seems like something that might reasonably be in scope.

**Comment by joshgoebel** [comment]
` K("Shift-Ctrl-u"), S("00A1"), K("Enter")`

If this is indeed universal across X11 (I think you said it was) then I think a `U` or `UC` (unicode char) helper would also be in-scope.

**Comment by joshgoebel** [comment]
@RedBearAK BTW, this is all well within in your power to build inside the config in Python - so even if I said "K is all you get, deal 😝" you could still build (and use) those nice abstractions yourself, AND in Kinto - so go for it... and when you have something workable we can look at a PR and how we'd get it into keyszer.

**Comment by joshgoebel** [comment]
Did you link me to some docs/writeup on this the other day, where are those?

**Comment by RedBearAK** [comment]
> U("U+00E0") vs U("00E0")

Well, my argument for retaining the `U+` would be primarily for the consistency of instantly knowing that what one is looking at is an actual Unicode address. When you go to look up Unicode in online tables, the Unicode address is always shown with `U+` in large letters, while other related codes are much smaller. Looks like CSS just puts a backslash instead of `U+` in front. 

AHK uses this directly, sending it in a format that basically treats it as if the entire Unicode address is a "key" (keys are often enclosed in curly braces): 

```
!1::Send, {U+00A1}
^Up::Send !{Up}
```

And of course when I saved all the Unicode info to my documentation I put it in the same format. The curly braces were not really necessary, but before I reformatted it to using GitHub Markdown tables it made it easier to visually separate the description, Unicode and Alt Code information. 

>Did you link me to some docs/writeup on this the other day, where are those?

You mean the repo I put up? It's really just a catalog of the names and codes of the special characters on the Apple keyboard. 

https://github.com/RedBearAK/optspecialchars/blob/main/Option-key-characters.md

If it were possible, the simplest form would be to just use the same curly braces construct as AHK, but I don't know how feasible that is: 

```
K("Alt+Key_1"): {U+00a1}
```

The Unicode number/address is hex, so the case should be irrelevant. 

> not interested in maintaining a full unicode mapping table inside the keymapper

I don't know why that would be necessary, the Unicode function should just be dedicated to sending out Shift+Ctrl+u and then "typing" the actual address and hitting "Enter". It should be up to the user to use a valid Unicode address to get what they want out of it. 

> a simple ASCII table for allow a S helper seems like something that might reasonably be in scope
> take S("00A1")... is that "a" or "A", and there is no capital "A" key key of course, it would be [shift, Key.A]

Seems like there should be a Python library that would make that easy, but I wouldn't even know how to look for it. I see how capital letters would make the output a bit more complicated to construct correctly, when the keymapper is designed to literally just send actual keystrokes. Unless there's a much simpler way to just paste literal ASCII strings like you're pasting from a clipboard? One would think so. Obviously you'd want to set a hard size limit and verify that the string is nothing but ASCII characters. 


> well within in your power to build inside the config in Python

I look forward to making very little progress on experimenting with that.

**Comment by joshgoebel** [comment]
Of course Python also has it's own way to encode unicode characters in strings: (just to throw it out there, not saying we should use this)

```
>>> "\u0394"
'Δ'
>>> "\u0034"
'4'
```
> to just use the same curly braces construct as AHK,   `{U+00a1}`

Of course that's not valid python, and I'm not sure "because AHK does it that way" is a great reason for an approach. :)

> I don't know why that would be necessary, 

Oh wait, maybe it actually wouldn't... LOL... you'd just type them one character at a time with the same encoding mechanism... what was I thinking....

> Seems like there should be a Python library that would make that easy,

I wouldn't call it difficult per se, I was just pointing out that it's not a 1 to 1 mapping like with ASCII...  Neither a U or S helper like you've described should be very complex to put together, hence my marking this "good first issue".  You mostly just need some loops and a large mapping table of say the lower ~100 ASCII chars into Key/Keys.

> I look forward to making very little progress on experimenting with that.

Do you not code at all or just not know Python?

**Comment by RedBearAK** [comment]
> Of course that's not valid python, and I'm not sure "because AHK does it that way" is a great reason for an approach. :)

No, I figured not. 

> Do you not code at all or just not know Python?

I feel like this is a bit of a false dichotomy. But with the difference between our apparent levels of ease in consuming documentation and understanding what code does, you may as well consider both to be true. And it probably will be until I manage to force myself to get through an entire YouTube crash course on Python, or some other "real" programming language more complex than HTML/CSS or simple shell scripts. 

My brain seems to need to see multiple working practical examples of something in action, where I can clearly see what just that part alone does, before I can actually **_understand_** how to use a programming construct. Before that it's just gibberish in most cases. You can feel free to think of this as a learning disability. 

On occasion someone in a forum will actually explain something in true layman's terms, describing what is **_really_** happening and why, and not just repeating the magic words, and then it will usually click right away. I think the key is that a good explanation banishes a bunch of incorrect assumptions. 

Unfortunately at my level a lot of the things you say still just sound like, "And then you just flim-flam the wing-whanger, and Bob's yer' Uncle! Easy!"

I'm sure I can do it on my own, as you suggest, but it will require more specific hints about exactly how to do certain parts, especially how to begin. And it will take time.

**Comment by joshgoebel** [comment]
> I feel like this is a bit of a false dichotomy. 

That's true. :-)  I was just trying to get a vibe for where you are in your journey to perhaps give some better guidance.

> consuming documentation and understanding what code does

Well, I've been doing this a LONG time... so don't feel bad or anything... I'd definitely recommend a crash course of some sort and then lots of playing and experimenting.  I'd recommend services like https://exercism.org/ where you can get 1-on-1 mentoring as well...  of all the languages out there Python is pretty easy to pickup.

Much of programming though is just breaking the problem down into smaller tasks... and thinking about how to solve it - that comes before any particular language... take something like `S("about:config")` for example... and you already know what you want at the end - a list of `K()` macros so you might come up with:

- get string input
- make an empty list
- split string into characters / loop over each character
  - convert each character into a `K()` combo
  - add combo to list
- return list

And each of those things could be googled to learn more... you might start with just a function that returns an empty list, then keep expanding it little by little.

```py
def S():
  return []
```

If course jumping into something longer (crash course, some mentoring) in the long-term may yield better results than just googling every tiny thing...

**Comment by joshgoebel** [comment]
To flesh that out more fully:

```
def S():
  return []

if (__name__=="_main"):
  result = S()
  print(result)
```

**Comment by joshgoebel** [comment]
Note (for fun) you can get CLOSE, since in Python {} is a set:

```py
U = 0
{U+0x00A1}
```

That is valid Python... but you have to turn the number into hex notation which takes away from the whole point just a bit. :)

**Comment by RedBearAK** [comment]
@joshgoebel 

When I used Shift or Ctrl as part of the shortcut, your branch is failing in the same way as the Kinto branch when doing a Unicode macro. It exits the Unicode entry mode after the first character, then outputs the final three characters of the Unicode address. I'm suspecting that somehow the Unicode entry is getting interrupted by receiving a release event for Shift or Ctrl when I lift the associated physical shortcut keys. 

So it appears the Kinto branch is not the only fork to fail at Unicode entry. Now I'm not so sure, even if I succeed at making a `UC()` function to process Unicode addresses, if that will completely bypass this problem with the Unicode entry mode failing. Since I'll just be building the same macro of `K()` wrapped objects that is currently failing.

**Comment by RedBearAK** [comment]
@joshgoebel 

```
>>> "\u0394"
'Δ'
>>> "\u0034"
'4'
```

Can this method be used to send Unicode characters directly to the output device? Without going through the whole [Shift+Ctrl+u, Unicode string, Enter], keystroke procedure?

**Comment by joshgoebel** [comment]
> your branch is failing in the same way as the Kinto branch 

As always, hard to say anything for sure without seeing a log... but if you turned your `suspend` timer down way low it's possible you've broken the good behavior... with suspend low you're going to be spewing all sorts of keypresses you don't need to the output.  The log would show you exactly what it's doing.  _With suspend high all of this is avoided._

This should technically be fixable with a 3rd timer and/or changed behavior for how we treat long sequences... right now a sequence is handled just as a bunch of discrete combos... which spews tons of uneeded output if keys aren't suspended going into the combos...

> Since I'll just be building the same macro of K() wrapped objects that is currently failing.

Exactly there is no magic, you'd first need to get the K() wrapped objects working, then work on a helper to make generating them easier.

**Comment by joshgoebel** [comment]
> Can this method be used to send Unicode characters directly to the output device?

UTF-8 is an encoding... those aren't keys (well except the very few that are), we can't simply type them because they don't exist on the keyboard.

**Comment by RedBearAK** [comment]
This sounds like something the proposed “post_combo” timeout would help avoid. I’ll try putting suspend back to 1 sec and see what happens. 

> we can't simply type them

So there’s no simple way around the fact that the program is set up to basically pretend to be an actual keyboard device. No putting a character in a clipboard and then typing Cmd-V? (I know, that would step on whatever the user might have in the clipboard at the time.) 

Will continue working on this tomorrow.

**Comment by joshgoebel** [comment]
> So there’s no simple way around the fact that the program is set up to basically pretend to be an actual keyboard device. 

That's what we do.

> that would step on whatever the user might have in the clipboard at the time

Just one of the problems... :-)

> This sounds like something the proposed “post_combo” timeout would help avoid.

Indeed or `output` could just be less stupid and a *little* more aware of sequences... it's likely quite a trivial fix that would really be a big win, hence my flagging it as a bug.

**Comment by RedBearAK** [comment]
@joshgoebel 

I have no idea where else to go with this. 

```python
import string


def UC(unicode_address):
    """Turn Unicode address into K() wrapped commands"""
    if (all(c in string.hexdigits for c in unicode_address) == False):
        print("ERROR: Invalid Unicode address string. Must be hexadecimal, 4 characters.")
        return
    elif len(unicode_address) != 4:
        print("ERROR: Invalid Unicode address string. Must be 4 characters in length.")
        return
    def UC_printer():
        key_list = []
        print('The key_list is now:', key_list)
        key_list.append('K("Shift-Ctrl-u")')
        print('The key_list is now:', key_list)
        for x in range(0, len(unicode_address)):
            key_list.append('K("' + unicode_address[x] + '")')            
            print('The key_list is now:', key_list)
        key_list.append('K("Enter")')
        print('The key_list is now:', key_list)
        return key_list
    return UC_printer
```

Output printing in log is: 

```
The key_list is now: []
The key_list is now: ['K("Shift-Ctrl-u")']
The key_list is now: ['K("Shift-Ctrl-u")', 'K("0")']
The key_list is now: ['K("Shift-Ctrl-u")', 'K("0")', 'K("0")']
The key_list is now: ['K("Shift-Ctrl-u")', 'K("0")', 'K("0")', 'K("a")']
The key_list is now: ['K("Shift-Ctrl-u")', 'K("0")', 'K("0")', 'K("a")', 'K("1")']
The key_list is now: ['K("Shift-Ctrl-u")', 'K("0")', 'K("0")', 'K("a")', 'K("1")', 'K("Enter")']
```

**Comment by joshgoebel** [comment]
You need to return actual objects not strings:

```py
key_list.append(K("Shift-Ctrl-u"))
key_list.append(K(unicode_address[x]))  
```

Of course that won't work exactly, don't you need `KEY_0` for numbers , etc? Your lookup table will need to get the names right based on the names in `key.py`... and you won't return a function, you'd just return the raw array.

**Comment by RedBearAK** [comment]
@joshgoebel 

Well, I don't know if this is actually the most correct way to do it, but this appears to work: 

```python
def UC(unicode_address):
    """Turn Unicode address hex string into keystroke commands"""
    if (all(c in string.hexdigits for c in unicode_address) == False):
        print("ERROR: Invalid Unicode address string. Must be hexadecimal, 4 characters.")
        return
    elif len(unicode_address) != 4:
        print("ERROR: Invalid Unicode address string. Must be 4 hex characters in length.")
        return
    combo_list = []
    combo_list.append(K("Shift-Ctrl-u"))
    for x in range(0, len(unicode_address)):
        if (str.isalpha(unicode_address[x])):
            combo_list.append(K(unicode_address[x]))            
        else:
            combo_list.append(K("KEY_" + unicode_address[x]))
    combo_list.append(K("Enter"))
    def UC_printer():
        return combo_list
    return UC_printer
```

Needs `import string` above it, or I'll have to do the hex check some other way instead of `string.hexdigits`, which is convenient because it has both upper and lowercase `A-F`.

**Comment by joshgoebel** [comment]
> I really don't understand why the two nested levels of functions are necessary,

The only place a list of commands is allowed is the top-level... 

```py
# would work
mapping: UC(...)
# does not work
mapping: [K("..."), UC(...), K("...")]
```

Because UC returns a list... and the command processing doesn't   know what to do with lists inside lists... but if you use a function/callback instead then that recursively calls handle_commands which (at the top-level) knows how to handle a list, so it just works.

The right solution is probably to handled nested lists OR flatten them... I'm not sure... but if it's working, that's a great start!

**Comment by RedBearAK** [comment]
> Now do some googling and see if there is a much simpler way to iterate over characters in a string... aren't strings iterable, just like an list?

I thought that's what it was already doing, and I got that from googling something like "iterate over characters in string" already, so not sure what I'll be looking for to do differently. Is it slower than some other solution? I'll look around. 

> Because UC returns a list... and the command processing doesn't know what to do with lists inside lists... but if you use a function/callback instead then that recursively calls handle_commands which (at the top-level) knows how to handle a list, so it just works.

> The right solution is probably to handled nested lists OR flatten them... I'm not sure... but if it's working, that's a great start!

Ah, so in its current form it won't work in a macro. I don't know how the recursive callback would work. I would definitely want this (and the generic string function) to work within macros. So is that something I should fix in `UC()` or would it make more sense to fix it elsewhere?

**Comment by RedBearAK** [comment]
@joshgoebel 

This what you meant by strings being iterable and simplifying the `for` loop? 

```python
def UC(unicode_address):
    """Turn Unicode address hex string into keystroke commands"""
    if (all(c in string.hexdigits for c in unicode_address) == False):
        print("ERROR: Invalid Unicode address string. Must be hexadecimal, 4 characters.")
        return
    elif len(unicode_address) != 4:
        print("ERROR: Invalid Unicode address string. Must be 4 hex characters in length.")
        return
    combo_list = []
    combo_list.append(K("Shift-Ctrl-u"))
    for x in unicode_address:
        if (str.isalpha(x)):
            combo_list.append(K(x))            
        else:
            combo_list.append(K("KEY_" + x))
    combo_list.append(K("Enter"))
    def UC_printer():
        return combo_list
    return UC_printer
```

**Comment by joshgoebel** [comment]
Yes it works if you return a function/callable like you currently are doing as it's currently implemented. If you simplified it and only returned the list that would be a problem.

**Comment by RedBearAK** [comment]
> Yes it works if you return a function/callable like you currently are doing as it's currently implemented. If you simplified it and only returned the list that would be a problem.

Now I see what you were getting at. 

And now I just need to figure out how to get the key labels from `key.py` the actual correct way, since the concatenation kludge I used for `UC()` worked solely because I was only dealing with the 0-9 numbers and nothing else besides `A-F`. It won't work for the generic string printer function. I'm not even sure how to approach that at the moment. I'll need to check every single character to make sure it's actually listed in `key.py` as a valid key, or add `Shift-key` for the ones that need that. Yes, yes, `dict`. But that's another level of understanding I need to reach. 

Other than simplifying the `for` loop, is there anything left that you would want to be fixed for the `UC()` function before I try to submit a PR?

**Comment by RedBearAK** [comment]
@joshgoebel 

> Other than simplifying the for loop, is there anything left that you would want to be fixed for the UC() function before I try to submit a PR?

Moved the function into `config_api` and it seems to be working fine. I put it just below `usleep` at the moment. Would it make more sense to put it just after the main `C()` function? I think it makes sense as a "helper" function. 

Since this will only work with `keyszer` anyway, might as well change all the `K()` I'm creating to `C()`.

**Comment by RedBearAK** [comment]
@joshgoebel 

FYI, I haven't added the `sleep` hack back into the v0.6.0 release version of `output.py`, but with this macro I'm testing with the Unicode characters I haven't been able to get it to have any kind of visible failure. Even holding the combo down and letting it build up a large buffer to eventually print out, it seems to have no particular issue with glitching. 

```python
    C("Shift-Alt-RC-u"): [C("Shift-slash"),UC("00a1"),UC("00a2"),UC("00a3"),C("Shift-slash"),C("Enter")],
```

The "Now is the time..." super long macro still glitches pretty easily though, without the `sleep` hack. But what I'm taking from this is that the entry of Unicode characters with this function should be pretty reliable. Actually kind of surprising it works this well, taking into account the somewhat delicate nature of the Unicode character entry procedure that caused it to fail completely with Kinto's `xkeysnail`. I've seen no indication yet of that kind of thing happening while using the `UC()` function. Even after forcing it to create a huge buffer of output.

**Comment by RedBearAK** [comment]
@joshgoebel 

I have a grandiose idea of supporting strings with any printable ASCII characters, but for now here is an `ST()` function that handles all uppercase and lowercase letters, spaces and numbers. It works. Let me know if you see any major problems with it. 

Seemed like a good idea to limit it to 250 characters per instance. Of course it can be repeated in a macro. But it's unlikely that a single unpunctuated string that length or longer will be needed. 

```python
def ST(str_to_type):
    """Turn alphanumeric string with spaces up to length of 250 characters into keystroke commands"""
    if len(str_to_type) >= 251:
        print("ERROR: String too long. Use some other solution for strings longer than 250 characters.")
        return
    if (str.isalnum(str_to_type.replace(" ", ""))) != True:
        print("ERROR: String contains non-alphanumeric characters. Not supported yet.")
        return
    combo_list = []
    for c in str_to_type:
        if c.isupper(): 
            combo_list.append(C("Shift-" + c))
        elif c == " ":
            combo_list.append(C("Space"))
        elif (str.isalpha(c)):
            combo_list.append(C(c))
        else:
            combo_list.append(C("KEY_" + c))
    def ST_printer():
        return combo_list
    return ST_printer
```

Tested with: 

```python
    C("Shift-Alt-RC-s"): [
        ST("Now is the time for 12345 good men to come to the aid of their country"),
        C("dot"),
        C("Enter"),
    ],
```

**Comment by RedBearAK** [comment]
@joshgoebel 

For consistency, would you rather I use `C() U() S()` function naming, or might we go with `CB() UC() ST()` from here on, for Combo/Unicode/String? I'm favoring the 2-character style. Seems awkward to mix the two naming styles. Just let me know if you want the new ones changed to `U()` and `S()`.

**Comment by RedBearAK** [comment]
@joshgoebel 

I'm noticing that I haven't been taking any extra steps to put double quotes inside the constructed `C()` objects, like this: 

```
            combo_list.append(C('"Shift-' + c + '"'))
```
Instead I just do this kind of thing, and it seems to work fine: 

```
            combo_list.append(C("Shift-" + c))
```

Is this not a potential issue under certain circumstances? It hasn't been causing any obvious problem, but makes me wonder if things really need to be in quotes inside every `K()/C()` function call.

**Comment by joshgoebel** [comment]
>   combo_list.append(C('"Shift-' + c + '"'))

That would simply be incorrect... the strings passed to C do not need to be double quoted.

**Comment by joshgoebel** [comment]
I'm confused though how can you type a 4 byte UTF-8 Unicode value with only 4 hex characters?

**Comment by RedBearAK** [comment]
@joshgoebel 

> go with long names

Really? That will make config files quite a bit more "verbose" than they are now. Seems a bit unnecessary for the main "processing" functions that get named so frequently. But it's your fork, you're in charge. 

So for someone to continue to support simpler naming they'd just put something like this at the top of their config file? 

```
CB = combo
ST = string_ascii
UC = unicode_char
```

Wouldn't it make a bit more sense to use either `char_unicode` and `string_ascii`, or `ascii_string` and `unicode_char`? I'm favoring the latter pairing. 

> I'm confused though how can you type a 4 byte UTF-8 Unicode value with only 4 hex characters?

Yeah, I'm probably using some improper terminology somewhere in there. I don't understand absolutely everything about the Unicode situation yet. For the 137 characters that I looked up for the Option key special character entry, everything fit within the U+0000 to U+FFFF range. So maybe I've just been dealing with 2-byte UTF-8 up to now. And I've read things that talked about the standard being 4 hex characters for compatibility between the encodings. But I may have misunderstood parts of that, and it may be that to support the entirety of Unicode beyond 2-byte UTF-8 the function will need to be tweaked to accept more than 4 hex characters. 

> That would simply be incorrect... the strings passed to C do not need to be double quoted.
> Those functions require strings... which need to be quoted.

So, you need to quote the stuff you put inside `C()`, to `type` it as a string, unless you're passing in something that's already typed as a string? I don't know how else to interpret this. 

> use a dict to lookup any remaining values (and add common ones, like `,`, `.`, etc...)

I thought about allowing periods and commas, but there's a whole selection of punctuation and printable characters that should be supported. That will just have to wait until I learn how to create the necessary `dict` and work with it.

**Comment by joshgoebel** [comment]
> That will make config files quite a bit more "verbose" than they are now. 

No, I'l keep `C` or remove the need to use it... and the others shouldn't be common.

>  just put something like this at the top of their config file?

Yes.

> I'm favoring the latter pairing.

Though ascii still bothers me since really `string` should probably just handle unicode characters itself... which works for both ASCII and unicode.

> will need to be tweaked to accept more than 4 hex characters.

Does the keyboard entry method support that?

> So, you need to quote the stuff you put inside C(), to type it as a string, 

A string _literal_, yes.

> unless you're passing in <del>something that's already typed as</del> a string? 

A string variable.  So always a string.

**Comment by RedBearAK** [comment]
> No, I'l keep C or remove the need to use it... and the others shouldn't be common.

That sounds great, actually. 

> Though ascii still bothers me since really `string` should probably just handle unicode characters itself... which works for both ASCII and unicode.

What, by looking for things like `\u00A1` within the string? 

> Does the keyboard entry method support that?

Looks like the keyboard method accepts up to six hex characters (and as few as one). After six nothing happens and it just waits for you to hit enter or escape. Which would match the U+10FFF I'm seeing everywhere for the the supposed maximum value for a Unicode code point. 

So I should rework that part of the Unicode function to allow for up to six hex characters. Probably should also limit it to evaluating as less than 10FFF in hex. 

I'll have to tackle this tomorrow.

**Comment by RedBearAK** [comment]
> If Unicode support is just added to string then you get this for free...

Not sure I understand this statement. Sounds like you're referring to the usual method of supporting Unicode in Python, but in this case we always have to take the raw hex characters and turn them into keyboard commands. Unless the Python Unicode support can just identify the Unicode part of the string, verify it and then pass it on in its original form? I can't imagine that's the usual way Python's Unicode support is used. 

> Don't forget you'll also need to add API docs to the README...

I figured that could wait until the form of the API has actually solidified. 

I keep typoing the U+10FFFF, apparently. It's four F's.

**Comment by joshgoebel** [comment]
Python has full support for encoding/decoding UTF-8, 16, etc... you just iterate over the string and each time you find a non-ASCII character you just calculate the hex codes and spit them out...

```py
>>> hex(ord("\u12ff") ) # 16-bit
'0x12ff'
>>> hex(ord("\U0010ffff") ) #  32-bit
'0x10ffff'
```

You can't actually write `\u10ffff` as that's just `\u10ff` folowed by `ff`, oe "off"... you'd have to use `\U`... but I'm not sure why you'd code them by hand if you had string support vs just typing the character into the string:

```
string("🚀💙")
```

```py
>>> [hex(ord(x)) for x in "🚀💙"]
['0x1f680', '0x1f499']
```

**Comment by RedBearAK** [comment]
@joshgoebel 

```python
string("🚀💙")
```

You want people to actually put Unicode characters directly into the config file? 

The story on the Windows side with AHK is that there was a major problem between the encoding Windows was using and the encoding of the `kinto.ahk` config file. Another user created a short block of code that just directly entered some pasted umlaut accented characters (for German) into their apps when using the associated shortcut sequence. Apparently this worked with no issue for the original user that created the PR. 

But when I tried to use the same code, my Win11 system would paste a couple of unrelated characters, rather than the correct accented character. Making sure the file was being saved as UTF-8 didn't help. The characters appeared correct in the config, but they would always come out wrong when using the shortcuts. 

This is why I initially tried bypassing this using Alt Code key sequences in AHK, to disconnect the actual character being inserted from the keys being used to enter the character, making the encoding of the file irrelevant. That worked, except for some apps like Notepad that didn't respond to a lot of Alt Codes. And there were a number of the special characters from the Mac keyboard that actually didn't have an Alt Code available, or the Alt Code was a special code that would only work in certain apps like MS Word with a different entry method. 

So I went with the much simpler Unicode method, that seemed to work much more universally. 

I don't know if it's possible to have this kind of character set mismatch problem with the config file in Linux, but I suspect that if the encoding of the config file were somehow accidentally changed when someone was editing it, they might end up having a similar issue with non-ASCII characters being decoded differently than intended. 

Unless this is just some stupid bug specific to Windows and AHK, and couldn't possibly cause a similar issue on the Linux/BSD side.

**Comment by joshgoebel** [comment]
> You want people to actually put Unicode characters directly into the config file?

Sure, if they want to.  That's really not so unusual.  Modern OSes and editors can handle Unicode just fine, as can Python.  Years ago this was all brand new and novel, but now it's old hat.    It sounds like AHK is perhaps just buggy with regard to it's Unicode support - but that has no reflection on Keyszer.

Looking forward to seeing a PR! :-)

**Comment by RedBearAK** [comment]
> Modern OSes and editors can handle Unicode just fine, as can Python.

That's what I thought too, until encountering this obnoxious encoding mismatch issue with AHK in Windows. When it gets to the point of writing up the new API info, I will at least be suggesting in the instructions that the user put an actual raw Unicode reference number in the string instead of the pasted literal symbol, if they want to be absolutely certain it will come out as expected regardless of what happens to the file. But I will also suggest that the literal symbol **_should_** work. 

> Looking forward to seeing a PR! :-)

Will get to that soon. Had to spend a lot of time this week learning how to set up a new pfSense router, and tuning the FQ_CoDel limiters to get our ADSL connection to work as well as it can.

**Comment by RedBearAK** [comment]
PR #60 only contains my functions in their currently working form. No new intelligence has been added at this time. `ST()` handles alphanumeric strings with spaces, `UC()` handles Unicode address hex references between 1 and 6 characters in length. It's testing fine with a 5-char hex address. 

```python
C("RC-Alt-Key_1"): UC("1f339"), # U+1F339 = rose emoji 
```

Not all apps actually support all the symbols from the extended Unicode space (above BMP), especially from more recent Unicode revisions (they're up to 15.0 now), but the rose emoji shows up fine in most apps I've tested. 

I know this is probably nowhere close to the form you ultimately want it to be in (I want that more intelligent string processor too) but it's the best I can do right now.

**Comment by RedBearAK** [comment]
@joshgoebel 

```
    """
    fix numerics being a special case and allows them to be accessed via
    Key["1"] just like any other normal key
    """
```

👼🏽 Love it.

**Comment by joshgoebel** [comment]
Can this be closed now since the PR was merged?

**Comment by RedBearAK** [comment]
> Can this be closed now since the PR was merged?

I think so. Adding potential future ability to handle Capslock and non-US layouts better is outside of the scope of this original issue. 

Closing as resolved.
