### ISSUE TITLE
None of my config is work.

### ISSUE THREAD

**Issue by zw963** [joshgoebel/keyszer#53]
**Describe the bug or unexpected behavior**
Please check my full config here. 

https://dpaste.com/AGB6C6BR7

Following is log when i start and pressing `Ctrl+f`.

```sh 
╰─ $ 2  keyszer --device /dev/input/event3 /dev/input/event4 -vvvv
keyszer v0.5.0
(DD) CONFIG: /home/zw963/.config/keyszer/config.py

(II) in LEFT_SHIFT (press)
(DD) on_key LEFT_SHIFT press
(DD) suspending keys [LShift<Key.LEFT_SHIFT>]

(II) in LEFT_SHIFT (release)
(DD) on_key LEFT_SHIFT release
(DD) resume because of mod release
(DD) resuming keys: [<Key.LEFT_SHIFT: 42>]
(OO) press LEFT_SHIFT
(OO) release LEFT_SHIFT
(--) Ready to process input.
(+K) Grabbing AT Translated Set 2 keyboard (/dev/input/event3)
(+K) Grabbing MOSART Semi. wireless dongle (/dev/input/event4)

(II) in LEFT_CTRL (press)
(DD) on_key LEFT_CTRL press
(DD) suspending keys [LCtrl<Key.LEFT_CTRL>]

(II) in LEFT_CTRL (repeat)
(DD) on_key LEFT_CTRL repeat

(II) in LEFT_CTRL (repeat)
(DD) on_key LEFT_CTRL repeat

(II) in F (press)
(DD) on_key F press
(DD) resuming keys: [<Key.LEFT_CTRL: 29>]
(OO) press LEFT_CTRL
(OO) press F

(II) in F (release)
(DD) on_key F release
(OO) release F

(II) in LEFT_CTRL (release)
(DD) on_key LEFT_CTRL release
(DD) resume because of mod release
(OO) release LEFT_CTRL
```

**Your setup**

- Python version: 3.10.5
- Keyszer version: 0.5.0
- Kinto version (if applicable):
- Devices `(+K)` we're handling input from:

/dev/input/event3  #  my builtin keyboard
/dev/input/event4  # my wireless keyboard.

**Expected behavior**

Should map `Ctrl+f` to `right` because following config when pressing C-f on firefox.

```
define_keymap(lambda wm_class: wm_class not in ("Emacs" "konsole" "alacritty" "kitty"  "Hyper" "Bcompare4"), {
    K("C-f"): with_mark(K("right")),
})
```

**Additional context**

All my config works well for xkeysnail.

**Comment by joshgoebel** [comment]
> ("Emacs" "konsole" "alacritty" "kitty"  "Hyper" "Bcompare4")

That syntax does not look right, that is just going to make one huge string, I think you want a tuple or an array.

> Keyszer version: 0.5.0

Please try with 0.6.0 release of `main`...

**Comment by joshgoebel** [comment]
> with_mark(K("right")),

Please also try a simpler test case without using `with_mark` and see if that works.

**Comment by zw963** [comment]
> > with_mark(K("right")),
> 
> Please also try a simpler test case without using `with_mark` and see if that works.

Can we make first code start work at first?

```py
define_modmap({
    Key.CAPSLOCK: Key.LEFT_CTRL,
    Key.RIGHT_ALT: Key.CAPSLOCK
})
```

because this really annoise me(i use Capslock for Left Ctrl).

BTW: this not add into any condition.

**Comment by joshgoebel** [comment]
I'm not sure what you are saying/asking with your last message.

**Comment by zw963** [comment]
> I'm not sure what you are saying/asking with your last message.

define_modmap({
    Key.CAPSLOCK: Key.LEFT_CTRL,
    Key.RIGHT_ALT: Key.CAPSLOCK
})

What i means is, above config do a config mapping, it make the capslock in my keyboard
behavior as left ctrl.

we can try make this code start to work at first,

because this line config not use with_mark, and not add into some lambda too.

**Comment by joshgoebel** [comment]
Try it in an empty config and it should work just fine... it likely won't work with Kinto because Kinto defines TWO conditional modmaps that will almost always replace it:

- not in a terminal
- in a terminal

So since one of those is almost always active your `modmap` will never work.

**Comment by zw963** [comment]
> Try it in an empty config and it should work just fine..

Yes, you are right, if my config only include following config, Ctrl+C mapping to Capslock works.

```
define_modmap({
    Key.CAPSLOCK: Key.LEFT_CTRL,
    Key.RIGHT_ALT: Key.CAPSLOCK
})
```

But, when i add any of left back, not works again.

**Comment by joshgoebel** [comment]
See my extended comment on why it's probably broken with Kinto and how you could fix it.

**Comment by joshgoebel** [comment]
Are you not using Kinto.sh?  I thought you were...

> Yes, you are right, if my config only include following config, Ctrl+C mapping to Capslock works.

Then you need to slowly add things to that minimal config until you find out at what point it stops working... ie _something LATER in your config is breaking things._

You'll need to experiment to find out what and then share the smallest possible config that still has the issue.

**Comment by joshgoebel** [comment]
> from xkeysnail.transform import *

Sorry I didn't notice that earlier - that's going to break everything. 

Please see: https://github.com/joshgoebel/keyszer/blob/main/UPGRADE_FROM_XKEYSNAIL.md

The Keyszer config does not require any sort of import like that... and importing Xkeysnail into Keyszer is just going to break everything.

I suggest copying your config and making Keyzer specific changes to the Keyszer config rather than trying to mix it with your existing config.  A lot of things will work as-is, but you can't just use exactly the same file.

**Comment by zw963** [comment]
Thank you for your's patience.

It seem like most of my config works. following is my new config:

```python
from evdev import ecodes
from keyszer import output
from evdev.uinput import UInput

output._uinput.close()
_keyboard_codes = ecodes.keys.keys() - ecodes.BTN
# create a new device with the exact options you want to mimic
output._uinput =  UInput(events={ecodes.EV_KEY: _keyboard_codes,
                                 ecodes.EV_REL: set([0,1,6,8,9]),
                                 },
                         name="Keyszer VIRTUAL mykeyboarddevice",
                         phys="isa0060/serio0/input0",
                         vendor=1,
                         product=1,
                         version=43841,
                         bustype=17,
                         input_props=[])

modmap("caps as control", {
    Key.CAPSLOCK: Key.LEFT_CTRL,
    Key.RIGHT_ALT: Key.CAPSLOCK
})

keymap("Mapping", {
    K("C-b"): with_mark(K("left")),
    K("C-f"): with_mark(K("right")),
    K("C-p"): with_mark(K("up")),
    K("C-n"): with_mark(K("down")),
    K("Alt-f"): with_mark(K("C-right")),
    K("Alt-b"): with_mark(K("C-left")),

    K("C-a"): with_mark(K("home")),
    K("C-e"): with_mark(K("end")),

    K("Alt-Shift-comma"): with_mark(K("C-home")),
    K("Alt-Shift-dot"): with_mark(K("C-end")),

    K("C-d"): [K("delete"), set_mark(False)],
    K("Alt-d"): [K("C-delete"), set_mark(False)],
    K("Alt-Backspace"): [K("C-Backspace"), set_mark(False)],

    K("C-g"): [K("esc"), set_mark(False)],

    K("C-k"): [K("Shift-end"), K("C-x"), set_mark(False)],

    K("C-slash"): [K("C-z"), set_mark(False)],

    # K("C-w"): [K("C-x"), set_mark(False)],
    K("Alt-w"): [K("C-c"), set_mark(False)],
    K("C-y"): [K("C-v"), set_mark(False)],

    K("C-KEY_2"): set_mark(True),
    K("C-Alt-space"): with_or_set_mark(K("C-right")),

  K("C-s"): K("C-f"),

    K("C-x"): {
      K("h"): [K("C-home"), K("C-a"), set_mark(True)],
    }
}, when = lambda wm_class: wm_class not in ("Emacs", "konsole", "Bcompare4"))

```

except the code for when, which i want to skip the class Emacs, maybe i am code somethings wrong?

```
, when = lambda wm_class: wm_class not in ("Emacs", "konsole", "Bcompare4"))
```

BTW:  I can ensure my emacs Class name is `Emacs`

**Comment by joshgoebel** [comment]
Trigger a combo from inside Emacs.  What does the verbose log show?

**Comment by joshgoebel** [comment]
>  when = lambda wm_class: wm_class not in ("Emacs", "konsole", "Bcompare4"))

Yes, that is wrong.  See the upgrading instructions and README for the correct API. `wm_class` is NOT passed directly, it's now inside a context object.

**Comment by joshgoebel** [comment]
> It seem like most of my config works. 

Great! Marking this issue as resolved then. :)

**Comment by zw963** [comment]
Cool, it work!

  There were a few times when I almost gave up because I had not used xkeysnail for a long time,  anyway, it works now!

Thank you very much!
