### ISSUE TITLE
Still too slow to daily usage. (xkeysnail have same issue too)

### ISSUE THREAD

**Issue by zw963** [joshgoebel/keyszer#54]
When enable keyszer, e.g. when i keep pressing down arrow key, it too slow to response.

that is, when i release my arrow key, the cursor still moving.

if not use xkeysnail, it will do response very quickly, when i finger live my keyboard, moving is stop immediately.

**Comment by zw963** [comment]
maybe we should use rust, golang or crystal instead to rewrite it.

**Comment by joshgoebel** [comment]
Oh I forgot about X lag... if you were using this over a non-local network (ie, not localhost) that might cause an issue, but locally I've not seen any lag like you're describing... My first guess is that it's the keyboard repeat rate.

**Comment by zw963** [comment]
In fact,  i used it in my emacs editor.

you are not told me how to run test ... i am tired ...

**Comment by joshgoebel** [comment]
It's just a python file...

```
python ./tests/perf.py
```

**Comment by zw963** [comment]
```
 ╰─ $ 130  PYTHONPATH=.. python ./tests/perf.py 
Traceback (most recent call last):
  File "/home/zw963/Dropbox/linux/utils/xkeysnail/site-packages/keyszer/./tests/perf.py", line 7, in <module>
    from keyszer.output import setup_uinput
ModuleNotFoundError: No module named 'keyszer.output
```

**Comment by joshgoebel** [comment]
Dunno, I'm quite new to Python (esp the packaging/building/install side)... I'm using a `venv` as shown in the [readme instructions](https://github.com/joshgoebel/keyszer#for-testinghackingcontributing)...

If you're installing some other way it might be different...

**Comment by zw963** [comment]
For run the test:

in fact, i run keyszer binary use following bash script sucessful.

```sh
export ROOT=${0%/*}/../
export PYTHONPATH=$ROOT/site-packages:$ROOT/site-packages/keyszer/src
name=$(basename $0)

$ROOT/site-packages/keyszer/bin/$name "$@"
```

the folder structure:

```
.
├── bin
│   ├── keyszer                 # < == this is my bash script.
└── site-packages
    ├── keyszer
    │   ├── bin
    │   ├── CODE_OF_CONDUCT.md
    │   ├── CONTRIBUTING.md
    │   ├── example
    │   ├── LICENSE
    │   ├── pyproject.toml
    │   ├── pytest.ini
    │   ├── README.md
    │   ├── SECURITY.md
    │   ├── src
    │   ├── tests
    │   ├── tools
    │   ├── UPGRADE_FROM_XKEYSNAIL.md
    │   └── USING_WITH_KINTO.md
```

Use this way, i can run keyszer successful, why i can not run test sucessful?

```
 ╰─ $ PYTHONPATH=/home/zw963/utils/xkeysnail/site-packages python tests/perf.py 
Traceback (most recent call last):
  File "/home/zw963/Dropbox/linux/utils/xkeysnail/site-packages/keyszer/tests/perf.py", line 7, in <module>
    from keyszer.output import setup_uinput
ModuleNotFoundError: No module named 'keyszer.output'
```

Where is the keyszer.output?

> But it's likely irrelevant... the real slowdown is X and I don't know how to measure/benchmark that easily in an automated fashion - but like I said: try fixing your repeat rate first and see if that helps.

That fine, my another laptop use Wayland, i can try it some day.

**Comment by joshgoebel** [comment]
> Where is the keyszer.output?

`src/keyszer/output.py`

> my another laptop use Wayland, 

We don't yet work with Wayland at all... 

**_Fix your repeat rate and see if that helps._**

**Comment by zw963** [comment]
```
xset r rate 200 20 
```

Ttthiiiiiiiiiiiiiiiiiiiiiissss   noottt woork

Maybbbbe ittt causeed by my laaaptooop speeciiiall isssssssssssssssssssssssssssueeee,

ABOVE CONTENT SHOULD BE:

this is not work
maybe it caused by my laptop special issue.


Hi, above content was input when i enable keyszer, as you can see, the lag cause
many char was output repeatedly.

maybe it caused by my laptop, maybe because my laotop too old, but anyway,
this issue is one of the main reason i give up to use xkeysnail.

**Comment by joshgoebel** [comment]
> Ttthiiiiiiiiiiiiiiiiiiiiiissss noottt woork

Well, it might be WAY too fast for you... You may want to read the man page and try different numbers.  The important thing is to get the speed synced up (I think).

- Run `xset r rate`
- startup `keyzser`
- Run `xset r rate` (again) 

> maybe it caused by my laptop special issue.

It's definitely possible something isn't right with your hardware or software... I haven't heard anyone else talking about issues like the ones you are describing.

**Comment by zw963** [comment]
vendor_id       : GenuineIntel
cpu family      : 6
model           : 60
model name      : Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz
stepping        : 3
microcode       : 0x28
cpu MHz         : 3800.000
cache size      : 6144 KB

memory 32G

disk * 2, both are SSD.

**Comment by joshgoebel** [comment]
More than fast enough.

**Comment by joshgoebel** [comment]
You could start benching individual functions to try and find where your speed is going:

```py
from .lib.benchit import benchit

@benchit
def on_event(event, device_name):
   # ...
```

Etc.

**Comment by joshgoebel** [comment]
I dug in here and fixed an issue where we weren't caching the X Display when we probably should be... resulting in an order of magnitude speed improvement.  Try the latest code from `main` and see if it helps.  

I wouldn't have called it slow before but I think it feels a LOT snappier now. :)

**Comment by zw963** [comment]
Okay, i will try it tomorrow.

**Comment by joshgoebel** [comment]
Any luck?

**Comment by zw963** [comment]
Sorry for late, i probably need some time to restore the context because time is pass a long time, and i use a new laptop, old config is missing...

**Comment by zw963** [comment]
Test use following new config:

```python
from evdev import ecodes
from keyszer import output
from evdev.uinput import UInput

output._uinput.close()
_keyboard_codes = ecodes.keys.keys() - ecodes.BTN
# create a new device with the exact options you want to mimic
output._uinput =  UInput(events={ecodes.EV_KEY: _keyboard_codes,
                                 ecodes.EV_REL: set([0,1,6,8,9]),
                                 },
                         name="Keyszer VIRTUAL mykeyboarddevice",
                         phys="isa0060/serio0/input0",
                         vendor=1,
                         product=1,
                         version=43841,
                         bustype=17,
                         input_props=[])

modmap("caps as control", {
    Key.CAPSLOCK: Key.LEFT_CTRL,
    Key.RIGHT_ALT: Key.CAPSLOCK
})

keymap("Emacs-like keys", {
    C("C-b"): with_mark(C("left")),
    C("C-f"): with_mark(C("right")),
    C("C-p"): with_mark(C("up")),
    C("C-n"): with_mark(C("down")),
    C("Alt-b"): with_mark(C("C-left")),
    C("Alt-f"): with_mark(C("C-right")),

    C("C-a"): with_mark(C("home")),
    C("C-e"): with_mark(C("end")),

    C("Alt-v"): with_mark(C("page_up")),
    C("C-v"): with_mark(C("page_down")),

    C("Alt-Shift-comma"): with_mark(C("C-home")),
    C("Alt-Shift-dot"): with_mark(C("C-end")),

    C("C-d"): [C("delete"), set_mark(False)],
    C("Alt-d"): [C("C-delete"), set_mark(False)],
    C("Alt-Backspace"): [C("C-Backspace"), set_mark(False)],
    C("C-k"): [C("Shift-end"), C("C-x"), set_mark(False)],

    C("C-g"): [C("esc"), set_mark(False)],
    C("C-q"): escape_next_key,

    C("C-slash"): [C("C-z"), set_mark(False)],

    C("C-w"): [C("C-x"), set_mark(False)],
    C("Alt-w"): [C("C-c"), set_mark(False)],
    C("C-y"): [C("C-v"), set_mark(False)],

    C("C-KEY_2"): set_mark(True),
    C("C-Alt-space"): with_or_set_mark(C("C-right")),

    C("C-s"): C("F3"),

    C("C-x"): {
        C("h"): [C("C-home"), C("C-a"), set_mark(True)],
        C("C-f"): C("C-o"),
        C("C-s"): C("C-s"),
        C("C-c"): C("C-q"),
        C("C-g"): ignore_key,
    }
}, when = lambda ctx: ctx.wm_class not in ("Emacs", "konsole", "Bcompare4"))
```

Performance is good, i don't know if because i changes from X11 to Wayland in my current laptop, anyway, i will enable it in recent days, if miss any issue, i will reopen this issue again.

Thank you very much for nice work!!
