### ISSUE TITLE
Option to "auto" deactivate the Mark in some situations

### ISSUE THREAD

**Issue by zw963** [joshgoebel/keyszer#57]
I have to describe this issue with some my config together to make it more clear.

I use emacs all the days, so, i expect to use same key keybinding.

a practice when use with emacs is, we used to set mark, then selection region, two steps

following is reproduce, with some screenshot for clear.

1.  my cursor before `emecs`, like this:
![image](https://user-images.githubusercontent.com/549126/175380423-7ca79623-bb2b-4d74-b8d9-e91bc4f67d12.png)

3.  Because `K("C-KEY_2"): set_mark(True)` config, when i pressing `Ctrl+2`, mark is set.

4. then i moving cursor,  you can see the highlight region get selected like this.
![image](https://user-images.githubusercontent.com/549126/175380235-07c96996-d3bd-4f3a-b5fe-df218ddcaf36.png)

5. Then, i input `emacs` to correct the typo

6. once  i start to typing, what i expected is, the set mark will cancel automatically, but that not true,

When i moving cursor forward, it still get highlight, like following, that not make sense.

![image](https://user-images.githubusercontent.com/549126/175381004-a07ebae6-d67e-403e-b5d2-6091c38217d0.png)

Can we have a way to make this deactive to be done automatically?

Thank you.

**Comment by joshgoebel** [comment]
> Can we have a way to make this deactive to be done automatically?

How might you encode/specify something like that in a general sense using the config file?

**Comment by joshgoebel** [comment]
Ping.

**Comment by zw963** [comment]
Sorry for late, i am a little busy recent days, you know, change those settings probably cause system keyboard issue, which may make use keyword as usual impossible, i will continue on this test soon.

Thank you very much!

**Comment by zw963** [comment]
Sorry for late again, any update on this?

What i expected is, when following case is happen, will auto deactivate the mark.

1.  set mark, then input new content, as describe by this issue
2. set mark, then copy the marked content with `M-w` done, as config by this:
    ```
    C("Alt-w"): [C("C-c"), set_mark(False)],
    ```
    because the purpose of set mark is just copy, now copy is done, so, mark is expected to deactivate automatically.

But, it seem like both of them still not supported, though, i can always use a `C-g`

```
C("C-g"): [C("esc"), set_mark(False)],
```
to deactive mark, anyway, it is enough if we can not support it.

Thank you.

**Comment by joshgoebel** [comment]
You never answered me:

> How might you encode/specify something like that in a general sense using the config file - any suggestions would need to be valid Python syntax?

I'm very interested in how a user might configure these things... I'm less interested in tons of complex behavior hidden inside the library itself...

`mark` is a generic concept for us that someone can use to build certain types of functionality - it's not meant to work "exactly" as it does anywhere else... obviously in a perfect world people would be able to configure it to work as they saw fit.

**Comment by zw963** [comment]
> You never answered me:
> 
> > How might you encode/specify something like that in a general sense using the config file - any suggestions would need to be valid Python syntax?
> 
> I'm very interested in how a user might configure these things... I'm less interested in tons of complex behavior hidden inside the library itself...
> 
> `mark` is a generic concept for us that someone can use to build certain types of functionality - it's not meant to work "exactly" as it does anywhere else... obviously in a perfect world people would be able to configure it to work as they saw fit.

I thought in the config `C("Alt-w"): [C("C-c"), set_mark(False)],`, `set_mark(False)` is do the exact the 2 does in my previous reply?

**Comment by joshgoebel** [comment]
Sorry, I'm not following... I'm asking how within the confines of the existing config we would add this 'auto" behavior.

**Comment by joshgoebel** [comment]
That turns the mark mode off.

**Comment by zw963** [comment]
> That turns the mark mode off.

May i misunderstood some things?

The really what i want is, when pressing `C-w`, will turns the mark mode off, right?

**Comment by joshgoebel** [comment]
set_mark *immediately* changes the state of the mark to True or False.

**Comment by zw963** [comment]
Yes, what i want is, when i pressing C-w, if mark is active, it should set mark to false.

e.g.

```
C("Alt-w"): [C("C-c"), set_mark(False)],
```

After i set mark and mark some content, when i pressing `Alt + w`(which is copy marked content), i expect the mark change to false, but this is not work,  i have to pressing `C-g` to set the mark to false.

**Comment by joshgoebel** [comment]
Please when filing issues always include your full config or at least the parts that seem relevant.  Please attach full config to this issue.

**Comment by joshgoebel** [comment]
> i expect the mark change to false

Are you sure it's not changing?  Changing the mark has NO effect on the cursor or selection - not until you'd move it.  So turning the mark off won't undo the current selection.

**Comment by zw963** [comment]
> Are you sure it's not changing? Changing the mark has NO effect on the cursor or selection - not until you'd move it. So turning the mark off won't undo the current selection.

Oops, it works, my fault. it just not deactive when tying.

**Comment by joshgoebel** [comment]
> it just not deactive when typing

Yes, there is no way to do that.  

Related: https://github.com/joshgoebel/keyszer/issues/66

I think if we added that, you could build the sort of functionality you're imagining...

**Comment by zw963** [comment]
> I think if we added that, you could build the sort of functionality you're imagining...

Okay, `deactive_mark_when_typing`, how about this name?

**Comment by joshgoebel** [comment]
I wasn't asking for a name per se, but rather how to add to the "per key" config.  We don't just do actions "while typing"... we do actions explicit when *certain* keys are hit.  I'm not even sure I want a "generic" key handler... but IF we did that see #66.

**Comment by zw963** [comment]
discuss on #66
