### ISSUE TITLE
Lack of tracking how many of the same modifier key are pressed

### ISSUE THREAD

**Issue by drjaska** [joshgoebel/keyszer#59]
Whenever 2 or more of the SAME modifier key are pressed from SEPERATE keyboards keyszer prints errors to console when keyszer is ran as the active user through CLI. The error is printed on key releases after the first release.

---

When keyszer is started with one modifier key held, the same key is pressed and then released again following error prints:

```
Exception in callback receive_input(InputDevice('...input/event6')) at /home/drjaska/.local/lib/python3.10/site-packages/keyszer/input.py:202
handle: <Handle receive_input(InputDevice('...input/event6')) at /home/drjaska/.local/lib/python3.10/site-packages/keyszer/input.py:202>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/drjaska/.local/lib/python3.10/site-packages/keyszer/input.py", line 215, in receive_input
    on_event(event, device.name)
  File "/home/drjaska/.local/lib/python3.10/site-packages/keyszer/transform.py", line 315, in on_event
    on_key(ks, context)
  File "/home/drjaska/.local/lib/python3.10/site-packages/keyszer/transform.py", line 384, in on_key
    transform_key(key, action, context)
  File "/home/drjaska/.local/lib/python3.10/site-packages/keyszer/transform.py", line 438, in transform_key
    reset_mode = handle_commands(keymap[combo], key, action, combo)
  File "/home/drjaska/.local/lib/python3.10/site-packages/keyszer/transform.py", line 531, in handle_commands
    _output.send_combo(command)
  File "/home/drjaska/.local/lib/python3.10/site-packages/keyszer/output.py", line 108, in send_combo
    missing_modifiers.remove(modifier)
  File "/usr/lib/python3.10/_collections_abc.py", line 741, in remove
    raise KeyError(value)
KeyError: Alt<Key.LEFT_ALT>
```

---

When 2 keys of the same modifier is pressed at the same time, the following is printed on 2nd modifier press's release.

```
Exception in callback receive_input(InputDevice('...input/event6')) at /home/drjaska/.local/lib/python3.10/site-packages/keyszer/input.py:202
handle: <Handle receive_input(InputDevice('...input/event6')) at /home/drjaska/.local/lib/python3.10/site-packages/keyszer/input.py:202>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/drjaska/.local/lib/python3.10/site-packages/keyszer/input.py", line 215, in receive_input
    on_event(event, device.name)
  File "/home/drjaska/.local/lib/python3.10/site-packages/keyszer/transform.py", line 315, in on_event
    on_key(ks, context)
  File "/home/drjaska/.local/lib/python3.10/site-packages/keyszer/transform.py", line 347, in on_key
    update_pressed_states(keystate)
  File "/home/drjaska/.local/lib/python3.10/site-packages/keyszer/transform.py", line 82, in update_pressed_states
    del _key_states[keystate.inkey]
KeyError: <Key.RIGHT_ALT: 100>
```

---

Ubuntu 22.04 with X11, xmonad as WM so no gnome DE. Keyszer is installed with `pip3 install --user --upgrade .` from this repo from main 93343e6 and ran as active user, uinput access is given with
```
sudo groupadd -f uinput
sudo gpasswd -a $USER uinput

cat <<EOF | sudo tee /etc/udev/rules.d/70-xkeysnail.rules
KERNEL=="uinput", GROUP="uinput", MODE="0660", OPTIONS+="static_node=uinput"
KERNEL=="event[0-9]*", GROUP="uinput", MODE="0660"
EOF
```
and I'm using keyboards with Scandinavian qwerty layout. IBus should be the keyboard input method framework as it's default in stock Ubuntu and I've not changed it myself though I don't load Gnome DE which may set it but `echo $GTK_IM_MODULE $QT_IM_MODULE` prints `ibus ibus`.

**Comment by joshgoebel** [comment]
> So this chain of inputs

Please provide the entire verbose log.

> AltGr 

What key are you calling AltGr?  This is a concept, not a key (according to the kernel)...

> Btw in this state keyszer is giving error prints, from not handling HV+Alt+AltGR modifier

Again shortest possible full verbose log would be nice to see.

**Comment by joshgoebel** [comment]
Also when in one of these "stuck" states, output from the DIAGNOSTICS key would be super helpful also.

**Comment by joshgoebel** [comment]
https://askubuntu.com/questions/656420/how-to-turn-caps-lock-into-altgr

If you're using one of these settings (using your Caps lock key as AltGr) then you probably cant ALSO use it as a custom modifier...

**Comment by joshgoebel** [comment]
> So this chain of inputs

This information is not high enough fidelity since it doesn't include any timing information.  It doesn't just matter which keys you hit but exactly how long you held them, etc... hence my asking for a full verbose log which include this detail.

**Comment by drjaska** [comment]
Alt Gr being right alt which differs from left alt by how it behaves. I don't know how it differs but keyszer references it as RIGHT_ALT or RALT in verbose logs.

I don't use multiple remappers at the same time as that sounds like asking for a bad time.

But apparently one of my unused but plugged in keyboards had somehow stuck its Right Alt key. When the PC is booted like that no other application had observable modifications outside of keyszer when first pressing shift and then capslock rebound to F20/F24 and it resumed pressing right alt.

Managing to get a right alt release signal without keyszer receiving a key down signal for it first gives the following error.

```
(II) in RIGHT_ALT (release)
(DD) on_key RIGHT_ALT release
(DD) resume because of mod release
Exception in callback receive_input(InputDevice('...nput/event10')) at /home/drjaska/.local/lib/python3.10/site-packages/keyszer/input.py:202
handle: <Handle receive_input(InputDevice('...nput/event10')) at /home/drjaska/.local/lib/python3.10/site-packages/keyszer/input.py:202>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/drjaska/.local/lib/python3.10/site-packages/keyszer/input.py", line 215, in receive_input
    on_event(event, device.name)
  File "/home/drjaska/.local/lib/python3.10/site-packages/keyszer/transform.py", line 315, in on_event
    on_key(ks, context)
  File "/home/drjaska/.local/lib/python3.10/site-packages/keyszer/transform.py", line 347, in on_key
    update_pressed_states(keystate)
  File "/home/drjaska/.local/lib/python3.10/site-packages/keyszer/transform.py", line 82, in update_pressed_states
    del _key_states[keystate.inkey]
KeyError: <Key.RIGHT_ALT: 100>
```

If I unplug that keyboard and start keyszer it works as intended.

If I use 2 other keyboards which don't have a problem with stuck keys I can replicate that same error if I press the same key down on both of them and when 2nd release happens it error prints.

I don't know how many people plan on using keyszer and pressing the same modifier key on 2 or more keyboards. The program doesn't crash when the error happens so it's not likely that it'll be a major issue for someone.

**Comment by joshgoebel** [comment]
> Managing to get a right alt release signal without keyszer receiving a key down signal for it first gives the following error.

Yes this is a rare edge case and can safely be ignored - in normal use keys don't release that were never pressed.  The state machine shouldn't be affected negatively by this type of error.

> one of my unused but plugged in keyboards had somehow stuck its Right Alt key.

That would be a problem.

>  if I press the same key down on both of them and when 2nd release happens it error prints.

To me this doesn't actually seem to be a thing that would happen in real life usage... There is no need to hold modifiers on two different keyboards simultaneously.

**Comment by drjaska** [comment]
I edited the issue's description and title due to the recent discoveries. I do not see providing more verbose logging as necessary in these time incensitive scenarios. The errors print whenever 2 of the same key are pressed so that the 2nd key is pressed before 1st key is released, error print happens on 2nd key's release.

**Comment by joshgoebel** [comment]
The error could easily be hidden but until I have more actual information considering how rare this is expected to be I'm inclined to leave it noisy to potentially aid in future troubleshooting.

**Comment by joshgoebel** [comment]
> When keyszer is started with one modifier key held, the same key is pressed and then released again following error prints:

```
Exception in callback receive_input(InputDevice('...input/event6')) at 
...
  File "/home/drjaska/.local/lib/python3.10/site-packages/keyszer/output.py", line 108, in send_combo
...
```

I'd still appreciate some additional detail here as even with two keyboards I can't reproduce a crash in `output.py`...

**Comment by joshgoebel** [comment]
> tried re-stucking the key and rebooting but I could not re-reproduce that output.py exception in 15 minutes of smashing keys. 

Well, thanks for the effort... the only way I can see that would happen (at a glance) if is someone had two of the SAME modifiers in a combo:

"Alt-LeftAlt-A"

The system gets confused if [left] alt is pressed because it tries to remove it twice, once for Alt and again for LeftAlt... but `K` should specifically prevent such things and you tiny example certainly didn't have anything like that.

**Comment by joshgoebel** [comment]
> Whenever 2 or more of the SAME modifier key are pressed from SEPERATE keyboards 

I think this is so much an edge case there isn't value in dealing with it.  In this case it only came up because of an actual hardware issue with the keyboard itself...

Right now I'm comfortable saying we just aren't compatible with someone who needs to use the SAME modifier MULTIPLE times across different keyboards...  Building a combo of different keys across multiple keyboards should be fine, just not hitting any arbitrary key on both keyboards AT ONCE.
