### ISSUE TITLE
Recommendations for combining WM_CLASS and WM_NAME? 

### ISSUE THREAD

**Issue by RedBearAK** [joshgoebel/keyszer#72]
@joshgoebel 

This isn't a bug, but I'm looking for some input on the most effective way to try and activate a combo only when within a specific app AND when a window of that app with a specific WM_NAME takes the focus. 

I just ran into a good example with SpaceFM. It's shortcuts are a mess and it does some binding of the keyboard whenever a menu is open, so macros won't work to get to menu items that don't have a direct hotkey combo assigned. I already have a set of shortcuts assigned to the main app, overriding some of the "General File Managers" shortcuts. 

```python
# Keybindings overrides for SpaceFM
# (overrides some bindings from general file manager code block below)
define_keymap(re.compile("spacefm", re.IGNORECASE),{
    C("RC-Page_Up"):            C("C-Shift-Tab"),           # Go to prior tab
    C("RC-Page_Down"):          C("C-Tab"),                 # Go to next tab
    C("RC-Shift-Left_Brace"):   C("C-Shift-Tab"),           # Go to prior tab
    C("RC-Shift-Right_Brace"):  C("C-Tab"),                 # Go to next tab
    C("RC-Shift-Left"):         C("C-Shift-Tab"),           # Go to prior tab
    C("RC-Shift-Right"):        C("C-Tab"),                 # Go to next tab
    C("RC-Shift-N"):            C("RC-F"),	                # Create new folder is Ctrl+F by default
    # Need to catch WM_NAME of "Find Files" and override Enter key state back to being Enter. 
    C("RC-F"):                  None,   # No direct shortcut available and menu macros don't work in SpaceFM.
    C("RC-Backspace"):          [C("Delete"),C("Enter")],   # Move to Trash (delete, bypass dialog)
    C("RC-comma"):              [C("Alt-V"),C("p")],        # Overrides "Open preferences dialog" shortcut below
    # This shortcut ^^^^^^^^^^^^^^^ is not fully working in SpaceFM. Opens "View" menu but not Preferences.
    # SpaceFM is doing some nasty binding that blocks all shortcuts, including Alt+Tab, while any menu is open.
},"Overrides for SpaceFM - Finder Mods")
```

If I'm going to activate the Enter-to-Rename feature for SpaceFM I need to be able to activate Enter-as-Enter when I see a window with a WM_NAME of "Find Files", so the Enter key behaves normally when that window is open. But as with many WM_NAME attributes this is pretty generic and also needs to be limited to the WM_CLASS of "spacefm" so that it won't accidentally apply to some other app window with the same WM_NAME. 

Would the suggested method for this be to have a completely separate `keymap` block that activates only on seeing both the WM_CLASS and WM_NAME, or to embed a nested `keymap` into the main `keymap` that just looks for the WM_NAME? Would nesting a `keymap` in this way even work? Or is it sort of a moot point since either way it would be an additional `keymap`? 

There may be a situation where it will make sense to look for a WM_NAME in general by itself, but most of the time it will be something like this that should only activate within the context of a specific app when that WM_CLASS/WM_NAME combination appears. 

Or should I just wrap the combo line in a `conditional()` inside the main `keymap` to limit it to working when the target WM_NAME is detected? 

Thoughts on the right way to do this?

**Comment by joshgoebel** [comment]
> Would the suggested method for this be to have a completely separate keymap block 

That's the easy way,  you can just use the normal KeyContext object you're passed to decide if the keymap applies or not.

> or to embed a nested keymap 

I'm not sure why it has to be nested, but that doesn't let you apply more conditionals.

It's possible a `cond()`  helper could be added that takes:

- a conditional function (that takes a keycontext object)
- a true combo
- a false combo

So it might look like:

```python
C("Cmd-A"):  cond(lambda ctx: ctx.blah and ctx.blah, C("Cmd-B"), C("Cmd-C"))
```

But honestly we should look at if there is any good reason why we couldn't just pass the KeyContext into EVERY user defined function... so you could pass a literal function reference:

```python
C("Cmd-A"):  cmd_b_or_c_combo_fn)
```

IE, every single combo could evaluate the key context and decide whether to take action and what action to take. If someone wanted a higher level `cond` helper, they could then write it themselves easily enough.

You'd have to pass the KeyContext all the way down into `handleCommand` and then around line ~543 just pass it into the command that was being called:

```
reset_mode = handle_commands(command(key_context), key, action)
```

Since commands currently aren't expected to take any arguments this shouldn't break anything (unless the helpers start breaking) in which case they might need to be updated to accept and ignore the context argument just so the params line up right, IIRC python is picky about such things.

**Comment by joshgoebel** [comment]
I'd be open to a PR exploring this as it sounds pretty useful and non-invasive.

**Comment by RedBearAK** [comment]
@joshgoebel 

Yeaaaah...

[ Lumbergh drinking coffee loop GIF ]

That all sounds really great. 

So, to receive the `key_context` into a custom function (if it were being passed) would it just be something like: 

```python
def myfunky_func(key_context):
```

Or would that even be necessary to have it accessible within the custom function? Would it just need a `global key_context`? 

Well, as long as a separate `keymap` isn't considered the "dumb/pointless" way, I can at least get started experimenting with the situations where it will be helpful for Kinto to detect WM_NAME.

**Comment by joshgoebel** [comment]
> would it just be something like:

Exactly, it's not a global.  It's passed around as needed.

> isn't considered the "dumb/pointless" way

Well it's the only way until someone comes along and implements this idea. :)

**Comment by RedBearAK** [comment]
@joshgoebel 

I'm noticing that it's not exactly simple to make sure that things match case insensitively with the new `when` criteria format compared to the older way I've been used to using with Kinto's config file. 

```python
define_keymap(re.compile("org.gnome.nautilus|nautilus", re.IGNORECASE),{

keymap("SpaceFM Find Files dialog", {
    C("Enter"): C("Enter"),
}, when = lambda ctx: ctx.wm_class.casefold() == "spacefm" and ctx.wm_name.casefold() == "find files")
```

If I were to leave a capital letter in the string in the first instance, it doesn't cause an issue since it's the string that's being casefolded to lowercase (if I understand correctly). So there will be a match. 

But if I try to match the casefolded context criteria to "Find Files", there will be no match, so I have to make sure I make the string all lowercase. 

What would be the simplest method to make this matching more robust so the user doesn't need to remember to make the string lowercase? The current examples in the README aren't doing any manipulation of the string, so any mistake in case will cause no match.

**Comment by joshgoebel** [comment]
> But if I try to match the casefolded context criteria to "Find Files", there will be no match

Right because "case fold" just means lowercase, AND lowercase and uppercase do not match.  But you can use regular expressions inside `when` if you want, it's just Python code, you can do anything you want to compare the strings...

> There must be a better way.

Write a helper function that returns a function that does the conditional calculations.  See the existing `wm_class_match` for some ideas.

> Tried to use the wm_class_match() helper

I returns the whole function, you can't combine it.  Usage:

```py
when =  wm_class_match("SpaceFM") 
``

But as mentioned earlier you could write your own function that returns a different conditional function...

**Comment by RedBearAK** [comment]
> I returns the whole function, you can't combine it.

I see. I’ll look into it. Seems ripe for some de-awkwardization.

**Comment by RedBearAK** [comment]
@joshgoebel 

What do you think about putting the `casefold()` here in `KeyContext`. 

```python
    @property
    def wm_class(self):
        self._query_window_context()
        return self._X_ctx["wm_class"].casefold()

    @property
    def wm_name(self):
        self._query_window_context()
        return self._X_ctx["wm_name"].casefold()
```

I know this would then require putting a `casefold()` on every string, but I feel like that should probably just be the recommended way of doing things. Just like Kinto has always used `re.IGNORECASE` everywhere and does `casefold()` when building comparison strings from WM_CLASS lists. When someone copies an existing list element or keymap definition to make a new one they can put whatever they want inside the quotes and not worry about getting the case exactly right. 

It at least makes the syntax a bit simpler: 

```python
}, when = lambda ctx: ctx.wm_class == "Dolphin".casefold() and ctx.wm_name == "Search".casefold())

Instead of: 
}, when = lambda ctx: ctx.wm_class.casefold() == "Dolphin".casefold() and ctx.wm_name.casefold() == "Search".casefold())
```

**Comment by joshgoebel** [comment]
KeyContext returns the actual given names.  I don't know why Kinto tests only against lowercase versions, but it seem obvious someone might want to test against the actual strings (with original case)... so that's what is returned by default.  Again, this is all just Python... if you don't like the verbosity you could:

- write your own string compare function (passing it both strings)

```py
}, when = lambda ctx: same_name(ctx.wm_class,"Dolphin") and same_name(ctx.wm_name,"Search")
```

- use regular expressions
- write an `augment` function that modifies keycontext (or replaces it entirely)
- replace `keymap` with your own version that wraps the original and returns whatever `KeyContext` object to the `when` callback that you feel is best 


Then share what you come up with on the wiki... I'm really hesitant to add a bunch of complexity for more advanced use cases when I still feel the right solution is for someone to learn a bit of Python (or consult a wiki page of pre-built solutions to more common problems)...

**Comment by joshgoebel** [comment]
Or even combine them:

```py
isWindow("Dolphin", "Search", ctx)
```

I think there are plenty of ways to wrap this nicely without needing to change the underlying context object.

**Comment by RedBearAK** [comment]
@joshgoebel 

Think this is good enough for a PR to add to `config_api`? Seems to work like I wanted. Couldn't quite figure out how to make the WM_NAME argument optional, but it's not too difficult to just put `None` in that spot. Or in the WM_CLASS spot, for that matter. 

```python
def isWindow(cls, nm):
    """
    Return WM_CLASS and WM_NAME match for current window, 
    casefolded for case insensitive matching against the 
    casefolded input arguments.
    
    Accepts regex patterns and literal strings.
    Requires at least one argument, other can be None.

    cls = WM_CLASS
    nm = WM_NAME
    """
    if cls != None:
        cls_rgx = re.compile(cls.casefold())
    if nm != None:
        nm_rgx = re.compile(nm.casefold())
    if cls == None and nm == None:
        raise ValueError("No valid argument given to isWindow")
    
    def cond(ctx):
        if cls != None and nm != None:
            return cls_rgx.search(ctx.wm_class.casefold()) and nm_rgx.search(ctx.wm_name.casefold())
        elif cls == None and nm != None: 
            return nm_rgx.search(ctx.wm_name.casefold())
        elif cls != None and nm == None: 
            return cls_rgx.search(ctx.wm_class.casefold())

    return cond
```

In use: 

```python
}, when = isWindow("^SpaceFM$", "Find Files"))

}, when = isWindow("^SpaceFM$", None))

}, when = isWindow(None, "Find Files"))

}, when = isWindow(cls = "^SpaceFM$", nm = "Find Files"))

}, when = isWindow(nm = "Find Files", cls = "^SpaceFM$"))

}, when = isWindow("DolPhin","SeArch"))
```

Works even with a deliberately mangled-case search string. Either argument can be `None`, but not both, of course. 

Since matching on these attributes is one of the primary ways of using the keymapper, and case is very seldom going to be a defining element (IMO, after seeing a large selection of these attributes), I think it's reasonable to include a function like this. If anyone wants to do a case sensitive comparison there are still the more direct methods available.

**Comment by joshgoebel** [comment]
> Think this is good enough for a PR to add to config_api? 

I'd say instead add it to the wiki in a `helpful config helpers` or something... Context is going to get more and more things (caplock status, etc)... I'm not (yet) I want helpers for every possible combo of conditions... it's really not that hard to just write a lambda... that's the "'cost" of having all the power of Python at ones disposal.  I'd like to see some more experimentation in this area before we add this to core.

The original "matchers" were only added to make upgrading from xkeysnail a little simpler...

**Comment by RedBearAK** [comment]
https://github.com/joshgoebel/keyszer/wiki/Helper-Function-Examples

This the kind of thing you're wanting to see in the Wiki?

**Comment by joshgoebel** [comment]
Why are we casefolding everything vs just using the `i` flag for insensitive character matching?  Wouldn't that be much simpler?

But yes, that was pretty much what I had in mind...

**Comment by joshgoebel** [comment]
Closing since we have this captured in the Wiki now.

**Comment by RedBearAK** [comment]
@joshgoebel 

> Why are we casefolding everything vs just using the i flag for insensitive character matching? Wouldn't that be much simpler?

All of the examples I'm finding with `(?i)` inside the original regex pattern, or `re.I` or `re.IGNORECASE` used as a flag parameter, show the `re` module being called directly in a different way, rather than the form I ended up using. 

```python
            return cls_rgx.search(ctx.wm_class.casefold()) and nm_rgx.search(ctx.wm_name.casefold())
```

I tried a few things that didn't work. Looks like in order to use those flags I would have to reformat how `re` was being used in general in the function, so that it would actually work like all the examples online. I'm probably missing something, as usual. But at the moment I don't see how replacing the casefolding with a flag would really make anything simpler. 

Although it might make sense for the main `isWindow` function to accept an optional parameter that changes whether the comparison is case sensitive or insensitive.

**Comment by joshgoebel** [comment]
When you compile the regex you just pass the flag:

```
pat = re.compile(engType+'(.*?)[Ss][Ee][Rr][Ii][Aa][Ll]',re.IGNORECASE)
```

**Comment by RedBearAK** [comment]
Updated the wiki with the expanded version of `isWindow` that allows for an optional "case" parameter to enable case sensitive matching if desired. By default it remains case insensitive. 

Adding the `re.I` or `re.IGNORECASE` flag works only with the initial `re.compile`, not with the `variable.search()` forms below it. I left everything the way it was in the case insensitive section since it works the same either way.

**Comment by joshgoebel** [comment]
> Adding the re.I or re.IGNORECASE flag works only with the initial re.compile

Yes, it modifies the generated regex, so it can only be done at compile time.
