### ISSUE TITLE
How to run it as a semi-privileged user

### ISSUE THREAD

**Issue by Ynjxsjmh** [joshgoebel/keyszer#74]
I'm following *ACL based permissions* instruction, add the new user and grant new user access. After doing all of these, when I run `keyszer`

```python
$ keyszer                                                                                                                                    

keyszer v0.6.0
(EE) Failed to open `uinput` in write mode.
Please check access permissions for /dev/uinput.
```

I try to change the owner and group of `keyszer` with `chmod keymapper:keymapper /path/to/keyszer`, but error still occurs.

Also in the following section, `keyszer.service` doesn't exists.

> #### systemd
>
> For a sample systemd service file for running Keyszer as a service please see [keyszer.service](https://github.com/joshgoebel/keyszer/blob/main/keyszer.service).

Sorry maybe I should choose *Request a new feature* rather than *Report a bug or unexpected behavior*.

**Comment by joshgoebel** [comment]
Did you setup and test your udev rules?

**Comment by Ynjxsjmh** [comment]
Thanks for the hinting, currently there are two lines in `/etc/udev/rules.d/90-keymapper-acl.rules`:

```
KERNEL=="event*", SUBSYSTEM=="input", RUN+="/usr/bin/setfacl -m user:keymapper:rw /dev/input/%k"
KERNEL=="uinput", SUBSYSTEM=="misc", RUN+="/usr/bin/setfacl -m user:keymapper:rw /dev/uinput"
```

When I run

```
$ /usr/bin/setfacl -m user:keymapper:rw /dev/input/%k
setfacl: /dev/input/%k: No such file or directory
```

I think I need to replace `%k` then I check `/dev/input/event*` it has 19 files from `event0` to `event18`, I decide to test it with `event0`

```
$ /usr/bin/setfacl -m user:keymapper:rw /dev/input/event0

setfacl: /dev/input/event0: Operation not permitted
```

Output of `getfacl` is

```
$ getfacl /dev/input/event0

getfacl: Removing leading '/' from absolute path names
# file: dev/input/event0
# owner: root
# group: input
user::rw-
group::rw-
other::---
```

I try to change the permission of ` dev/input/event0` to 777 but the error still the same.

Then I try to run `/usr/bin/setfacl -m user:keymapper:rw /dev/input/event0` as `sudo` and it works now

```
$ getfacl /dev/input/event0

getfacl: Removing leading '/' from absolute path names
# file: dev/input/event0
# owner: root
# group: input
user::rw-
user:keymapper:rw-
group::rw-
mask::rw-
other::---
```

After `sudo` the same for `uinput`, run `keyszer` in the shell results in the same error.

**Comment by joshgoebel** [comment]
Yes, these input devices are secure pieces of the system. You need to run the command within udev - which should already be running as root. 

Sudo should work though but it'll just break after you reboot. 

Once you get the permissions correct are you running keyszer as the keymapper user?

**Comment by Ynjxsjmh** [comment]
```
$ su keymapper -c "/home/winy/.local/bin/keyszer"
Password:
bash: line 1: /home/winy/.local/bin/keyszer: Permission denied

$ ll /home/winy/.local/bin/keyszer
-rwxr-xr-x 1 keymapper keymapper 209 Aug  6 13:14 /home/winy/.local/bin/keyszer*
```

I use `su` to run `keyszer` as another user, but it says permission denied when the permission is `x` for other user.

**Comment by joshgoebel** [comment]
What is the shebang line? Does it exist on your system?

**Comment by Ynjxsjmh** [comment]
If you mean `#!/usr/bin/env bash` at the top of script, when I execute it, it evals a new bash,

```
$ /usr/bin/env bash
[winy@thinkpad ~]$
```

Is this necessary in the files referred in *ACL based permissions (narrow, more secure)* section?

**Comment by joshgoebel** [comment]
What is the full content of local bin keyszer?

**Comment by Ynjxsjmh** [comment]
Then content of `/home/winy/.local/bin/keyszer` is

```python
#!/usr/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from keyszer.cli import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

I get this by following

> ## From source
> Just download the source and install.
> ```
> git clone https://github.com/joshgoebel/keyszer.git
> cd keyszer
> pip3 install --user --upgrade .
> ```

**Comment by joshgoebel** [comment]
Maybe su first. Then once you already have a shell prompt as key mapper try running it?

It's gonna be something really stupid simple. And it looks like bash is throwing the error, not keyszer.

**Comment by Ynjxsjmh** [comment]
Thanks, I need to reload my udev rules after adding `/etc/udev/rules.d/90-keymapper-acl.rules` with:

```
$ sudo udevadm control --reload-rules
$ sudo udevadm trigger
```

Then follow the step 1) create user `keymapper` 2) `su` to it 3) pip install `keyszer` in this user.

Then when I'm on other user, I run following script to run `keyszer`

```
$ su keymapper -c "/home/keymapper/.local/bin/keyszer"   
```

Is this the way you want to mention in README?

**Comment by Ynjxsjmh** [comment]
After I run the `keymapper`, everytime I type a key, it throws error

```
$ su keymapper -c "/home/keymapper/.local/bin/keyszer -c ~/config2.py"

keyszer v0.6.0
(EE) Can't connect to display ":0": b'Authorization required, but no authorization protocol specified\n'
(EE) Can't connect to display ":0": b'Authorization required, but no authorization protocol specified\n'
(--) Autodetecting all keyboards (--device not specified)
(+K) Grabbing AT Translated Set 2 keyboard (/dev/input/event3)
(+K) Grabbing USB GAMING MOUSE  Keyboard (/dev/input/event5)
(--) Ready to process input.
(EE) Can't connect to display ":0": b'Authorization required, but no authorization protocol specified\n'
f(EE) Can't connect to display ":0": b'Authorization required, but no authorization protocol specified\n'
(EE) Can't connect to display ":0": b'Authorization required, but no authorization protocol specified\n'
f(EE) Can't connect to display ":0": b'Authorization required, but no authorization protocol specified\n'
(EE) Can't connect to display ":0": b'Authorization required, but no authorization protocol specified\n'
f(EE) Can't connect to display ":0": b'Authorization required, but no authorization protocol specified\n'
(EE) Can't connect to display ":0": b'Authorization required, but no authorization protocol specified\n'
f(EE) Can't connect to display ":0": b'Authorization required, but no authorization protocol specified\n'
(EE) Can't connect to display ":0": b'Authorization required, but no authorization protocol specified\n'
```

Content of `config2.py` is

```
# define timeout for multipurpose_modmap
timeouts(multipurpose = 1)

# [Global modemap] swap LWin and LCtrl
modmap('swap left win and left ctrl', {
    Key.LEFT_META: Key.LEFT_CTRL,
    Key.LEFT_CTRL: Key.LEFT_META,
})

keymap(None, {
    K('APOSTROPHE'): {                  # '
        K('w'): Key.KEY_1,
        K('e'): Key.KEY_2,
        K('r'): Key.KEY_3,
        K('s'): Key.KEY_4,
        K('d'): Key.KEY_5,
        K('f'): Key.KEY_6,
        K('x'): Key.KEY_7,
        K('c'): Key.KEY_8,
        K('v'): Key.KEY_9,
        K('g'): Key.KEY_0,
    },
})
```

**Comment by joshgoebel** [comment]
See https://github.com/rbreaves/kinto/blob/master/linux/xkeysnail.service

You need to use `xhost` from the current logged in used to grant the `keymapper` user permission to access your X session.

```
/usr/bin/xhost +SI:localuser:keymapper
```

I think?

**Comment by Ynjxsjmh** [comment]
Thank your, this is the right solution, I need that before running `keyszer`

```python
$ /usr/bin/xhost +SI:localuser:keymapper
$ su keymapper -c "/home/keymapper/.local/bin/keyszer -c ~/config2.py"
```

**Comment by rbreaves** [comment]
Yea those instructions on how to get uinput working are inadequate to actually get it working on Ubuntu or Ubuntu Budgie 22.04 at the very least. I have ended up installing it under sudo for now just so I can work on more pressing issues on getting Kinto ported over - but this will need to be worked out so that uinput permissions will work as it should for the keymapper user.

I like the attempt to make it work - but I am really at a loss on why it does not work as I have followed the readme to a T, and the suggestions in this thread as well. Either way to get the dev work done I will not be working under the keymapper user itself - fine for the final product but not while dev'ing it out imo because I am not going to point vscode or my code editors into a limited user path and all that mess.

What I have documented to get things installed.

```
# reqs on ubuntu
sudo apt update
sudo apt install python3-venv python-is-python3

# -m will create home directory
sudo adduser -m keymapper
# if you forgot
sudo mkhomedir_helper keymapper
sudo su keymapper
bash
cd ~
git clone git@github.com:rbreaves/keyszer.git
cd keyszer
python3 -m venv .venv
source .venv/bin/activate
pip3 install -e .
# if this fails the sudo may be required - under non-keymapper user
# sudo pip3 install -e .
# --very-bad-idea if using sudo
./bin/keyszer -c config_file


sudo cp /home/rreaves/.config/kinto/kinto-keyszer.py /home/keymapper/kinto-keyszer.py
sudo chown keymapper:keymapper /home/keymapper/kinto-keyszer.py
./bin/keyszer -c /home/keymapper/kinto-keyszer.py
```

I currently have an error in my config file itself - but this is a good start.

**Comment by rbreaves** [comment]
So I have had my first success with running keyszer! Unfortunately the very first combo I tried failed - but I kinda figured it might be problematic as I believe you based your code on the latest xkeysnail and despite some of our prior conversations I kinda the sticky implementation might not fully be what it needs to be when multiple modifiers are pressed.

What worked for me
```
sudo DISPLAY=:0 ./bin/keyszer -v --very-bad-idea -c ~/.config/kinto/kinto-keyszer.py
```

Also had to replace all mentions of M with Alt - but I recalled us discussing that awhile ago - but I did forget initially and was commenting out lines at first lol.

So the combo that gave me heartache earlier was Ctrl-Shift-Left/Right in Sublime Text. It doesn't highlight the entire line in either direction. I use this pretty heavily, as do many programmers I assume - although VSCode... I have no idea what it uses without looking at the documentation because I port over my sublime remaps even into VSCode.

```
(DD) WM_CLS 'Sublime_text' | DV 'AT Translated Set 2 keyboard' | KMAPS = [anonymous keymap, General GUI, Wordwise - not vscode, Sublime Text]
(DD)   COMBO: LShift-LSuper-DOWN => Alt-Shift-DOWN [Sublime Text]
(DD) spent modifiers [<Key.LEFT_SHIFT: 42>, <Key.LEFT_META: 125>]
(DD) resuspending keys
(DD) suspending keys [LShift<Key.LEFT_SHIFT>, LSuper<Key.LEFT_META>]
(OO) press LEFT_ALT
(OO) press LEFT_SHIFT
(OO) press DOWN
(OO) release DOWN
(OO) release LEFT_SHIFT
(OO) release LEFT_ALT

(II) in DOWN (release)
(DD) on_key DOWN release
(DD) resuming keys: [<Key.LEFT_SHIFT: 42>, <Key.LEFT_META: 125>]
(OO) press LEFT_SHIFT
(OO) press LEFT_META
```

I am also doing this dev work over x11vnc w/ Ubuntu Budgie and it appears to be passing my raw keyboard input perfectly. It is kinda funny though - because it means I get to keep my host local machine running with macOS while dev'ing it out lol. Also linked up my hot corners and hot keys to toggle the terminal of my mac instead of the linux OS.

**Comment by joshgoebel** [comment]
>  I kinda the sticky implementation might not fully be what it needs to be when multiple modifiers are pressed.

Remember nothing is sticky at all unless you manually tell it to make it so using `bind`.

**Comment by joshgoebel** [comment]
> So the combo that gave me heartache earlier was Ctrl-Shift-Left/Right in Sublime Text. It doesn't highlight the entire line in either direction. 

Do you mean Cmd-left/right?  Highlights to the beginning/end of the line for me here in Sublime...

**Comment by joshgoebel** [comment]
> --very-bad-idea

Keyszer should be just as secure (or insecure) as xkeysnail, but of course I just despise this running as root... I'm happy to help as much as I can but I did figure that some of the work across distros (and permission) regarding uinput and such things might fall to you to figure out (if you switch away from root)...  

Of course I'd love our README to cover "all the cases" so PRs there are certainly welcome.  I'm on Arch myself and I've tested under a separate user just enough to confirm it can and does work fully in that scenario.

**Comment by joshgoebel** [comment]
If you start to have separate notes/issues feel free to just create new issues here vs using this as a "capture all" thread... having separate issues will make it much easier to keep discussion separate and coordindate any fixes necessary - plus this thread is far long enough already. :)

**Comment by rbreaves** [comment]
Oh I do plan to make some PRs soon w/ some updated info & sure I don’t mind working out the permission issues for Ubuntu distros.

If I recall you use Arch? So I kinda assume that might be why it didn’t just sorta work for me 😅. But yea - till the permission issue is resolved I will be holding off on merging the changes into the master branch of Kinto.

At the same time - I’m more motivated to just getting the key remaps fully working as expected - then I’ll circle back to the permission issues. Besides that if I need some changes, advice or assistance in other areas then I need to vet that stuff out, so atm I’d rather scope out the work that’ll need to be done before hyper focusing on permission issues.

**Comment by joshgoebel** [comment]
A totally sane plan.

**Comment by rbreaves** [comment]
> Remember nothing is sticky at all unless you manually tell it to make it so using `bind`.

Just now sitting down to really read all of this and yes.. that very well may be the issue actually, just need to add bind to that as well. Will also take a peak at what RedBear posted somewhere else. I added bind to the Tab remaps already as suggested in your readme - but not sure why I didn't think to do that to all multi modifier remaps in general.

**Comment by joshgoebel** [comment]
What other multi modifier remaps do you feel it's required for?

**Comment by rbreaves** [comment]
> What other multi modifier remaps do you feel it's required for?

Rest of this convo will be in this thread. In general though I think there's been a misunderstanding between how you and I have envisioned a or the binding function to operate. We'll need to figure something out there or this will be breaking for Kinto as it relies heavily on all modifier keys sticking till the user lets up on them.

https://github.com/joshgoebel/keyszer/issues/95
