### ISSUE TITLE
[BUG] Many errors in log when disconnecting USB keyboard

### ISSUE THREAD

**Issue by RedBearAK** [joshgoebel/keyszer#77]
As title says, when I disconnect a USB keyboard while `keyszer` is running, I get a ton of stacktrace errors in the log. These are not resolved by plugging the USB keyboard back in. 

```python
Exception in callback receive_input(InputDevice('...nput/event16')) at /home/kris/Downloads/josh-keyszer/keyszer/src/keyszer/input.py:102
handle: <Handle receive_input(InputDevice('...nput/event16')) at /home/kris/Downloads/josh-keyszer/keyszer/src/keyszer/input.py:102>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/kris/Downloads/josh-keyszer/keyszer/src/keyszer/input.py", line 103, in receive_input
    for event in device.read():
  File "/home/kris/Downloads/josh-keyszer/keyszer/.venv/lib/python3.10/site-packages/evdev/eventio.py", line 71, in read
    events = _input.device_read_many(self.fd)
OSError: [Errno 19] No such device
```

I haven't really examined this in depth. It just seems like `keyszer` is not correctly letting go of the device when it is no longer available.

**Comment by joshgoebel** [comment]
> These are not resolved by plugging the USB keyboard back in.

I'm not sure what this means... are you saying unplugging a keyboard borks the whole service?

**Comment by RedBearAK** [comment]
Weird, now I can't seem to replicate the issue. I know I've seen it before, back when I was doing a lot of testing of the AZERTY keyboard. 

I'll add to this if it comes up again.

**Comment by RedBearAK** [comment]
OK, I was able to replicate it by having the external USB plugged in when starting up, and then unplugging it. 

The funny thing about this is that it doesn't actually stop the keyboard from working. The service doesn't crash. But the external keyboard no longer gets remapped since the connection from `keyszer` to the device was lost. 

The errors in the console just keep repeating endlessly, even when I'm not typing anything. Definitely some kind of loop happening.

**Comment by RedBearAK** [comment]
I just tried a different USB (PC) keyboard, same symptoms. 

As noted in the PR about Capslock and Numlock, when I'm plugging in a USB keyboard while `keyszer` is running, the external keyboard doesn't react properly. That appears to be because the device isn't actually being acquired (grabbed) by `keyszer` on the fly. It works fine as far as the OS or X11 is concerned, but nothing is remapped. Of course that includes the lock key functions I was trying to test. 

So if the device is present at startup, everything is fine, but not if I plug something in after startup or unplug a device that was present at startup. 

This would never come up with the internal keyboard since it can't be disconnected. 

I can't imagine what could possibly be causing this.

**Comment by joshgoebel** [comment]
Probably just a bug in the code, I'll see if I can't reproduce... last time I played with all this was working but there are no automated tests for the low-level hardware stuff.

**Comment by RedBearAK** [comment]
Oh, one of the things that happened during testing is that I tried to use Ctrl+C to quit the process before attempting the bailout key, and it just started endlessly repeating "^C^C^C^C^C^C^C..." in the terminal. And also the bailout key failed to work, so it was one of those occasions where I had to close the terminal tab in order to finally terminate the process. 

That's actually happened to me on numerous occasions. And Ctrl+C basically has never worked, so it was just a quirk that I even tried it in this case. I'm wondering if there isn't a more reliable place to put the debug/bailout key action. Or maybe even multiple places inside some of the main loops that happen, so it can't fail to work so easily. It seems to get stuck in loops somewhere and never re-evaluates whether the debug key has been used. 

Wonder if a loop iteration counter could be used to help mitigate these kinds of errors that make it difficult to exit the process cleanly.

**Comment by joshgoebel** [comment]
> And also the bailout key failed to work,

Weird, works here fine, even after unplugging USB and getting tons of errors...

**Comment by joshgoebel** [comment]
2ab5e3d Please test.

**Comment by RedBearAK** [comment]
> https://github.com/joshgoebel/keyszer/commit/2ab5e3df91cf98ebfd481c0f08a753850c935454 Please test.

Well, the error cycle doesn't appear any more in the terminal when disconnecting a "grabbed" external USB keyboard. So no problem quitting the process with the debug key, even if it was necessary. 

The problem of a newly connected USB device not getting dynamically "grabbed" is still there. It will only get picked up if it's connected at startup. If that's not happening to you there must be something weird with my setup. 

Ctrl+C is still not working to kill the process, and it did the repeating thing again, even after this change (and without needing to plug in and remove a USB keyboard first). Which once again made the debug key ineffective. Must be an unrelated issue.

**Comment by joshgoebel** [comment]
> The problem of a newly connected USB device not getting dynamically "grabbed" is still there. 

Maybe play around with adding some logging to `device_change` and post anything you learn in a new issue?  When i fixed unplugging it was with a keyboard I had just plugged in (that was auto-detected and grabbed just fine).

**Comment by joshgoebel** [comment]
```
(II) in BTN_MOUSE (release)
(DD) on_key BTN_MOUSE release
(OO) release BTN_MOUSE

(II) in LEFT_CTRL (press)
(DD) on_key LEFT_CTRL press
(DD) suspending keys [LCtrl<Key.LEFT_CTRL>]

(II) in C (press)
(DD) on_key C press
(DD) resuming keys: [<Key.LEFT_CTRL: 29>]
(OO) press LEFT_CTRL
(OO) press C
signal INT received
(OO) release LEFT_CTRL
(OO) release C
```

Works here.

**Comment by joshgoebel** [comment]
I'm going to call this issue closed, feel free to open others as needed.
