### ISSUE TITLE
Conditional modmap not working as expected

### ISSUE THREAD

**Issue by RedBearAK** [joshgoebel/keyszer#84]
I thought I would try to do the remap of the base numpad keys with Numlock OFF that prompted me to want access to Numlock status in the first place. But I'm not having any luck getting a modmap to activate. I've tried the older form (define_conditinal_modmap) and also the newer form with just `modmap` surrounded by `conditional`. I gave it a goofy remap to make it more obvious when it becomes active, but it just never seems to activate. The numpad nav keys are always nav keys, and the 5 key has no output when Numlock is OFF. 

This is weird, because if I uncomment the first test keymap it's still doing what I expect, changing the output of the Numpad 5 key only if Numlock is OFF. But the modmap, whether it's wrapped in a conditional or I just put the same criteria in a `when` at the end of the modmap, just doesn't seem to react the same way. 

The way this is set up it shouldn't try to be active when the "Mac Numpad" feature is engaged, but as soon as I turn that off this should be active. But even removing that as part of the criteria to make it more like the initial test example here doesn't seem to help. 

Any ideas what I'm doing wrong? 

```python
# keymap("Test of numlock state", {
#     C("KP5"): ST("KP5 with numlock_on is False"),
# }, when = lambda ctx: ctx.wm_class not in remotes and ctx.numlock_on is False)


conditional(
    lambda ctx: ctx.wm_class not in remotes and ctx.numlock_on is False and _mac_numpad is False, 
    modmap("Numpad fix for GTK apps", {
    # This should use some kind of conditional modmap: 
        # # Fix Numpad base nav keys and shortcuts in GTK apps (when Mac Numpad feature disabled and Numlock is OFF)
        Key.KP5:    Key.X,
        Key.KP9:    Key.Y,
        Key.KP3:    Key.Z,
        Key.KP7:    Key.A,
        Key.KP1:    Key.B,
        Key.KP8:    Key.C,
        Key.KP2:    Key.D,
        Key.KP4:    Key.E,
        Key.KP6:    Key.F,
        # Key.KP5:    Key.KEY_5,
        # Key.KP9:    Key.PAGE_UP,
        # Key.KP3:    Key.PAGE_DOWN,
        # Key.KP7:    Key.HOME,
        # Key.KP1:    Key.END,
        # Key.KP8:    Key.UP,
        # Key.KP2:    Key.DOWN,
        # Key.KP4:    Key.LEFT,
        # Key.KP6:    Key.RIGHT,
    })
)
```

**Comment by joshgoebel** [comment]
Start with the code that works and then add to it one piece/line at a time until it breaks to find out where the problem is.

**Comment by RedBearAK** [comment]
Now I have a headache. Need some verification here. 

* Modmaps are mutually exclusive. Was confused because Kinto has dual modmaps. 
* Kinto's dual modmaps only work because they operate in mutually exclusive circumstances. 
* Ergo, I must create mutually exclusive circumstances that also include the state of the Numlock key. 
* This will produce four (semi-redundant) non-interfering modmaps instead of two. 
    * Not in terminals with numlock_on == True
    * Not in terminals with numlock_on == False
    * Only in terminals with numlock_on == True
    * Only in terminals with numlock_on == False

This will also require converting all existing modmaps to the new format, or at least somehow modifying the lambda in the existing modmaps to allow access to `numlock_on` property. Although that may be as simple as just changing "lambda wm_class:" to "lambda ctx:". 

Anything wrong with this thinking?

**Comment by joshgoebel** [comment]
Sounds correct. I'd be open to a discussion about "concurrent" mod maps but not sure how you'd resolve conflicts. If you wanna have that discussion open a separate issue.

**Comment by RedBearAK** [comment]
> Sounds correct. I'd be open to a discussion about "concurrent" mod maps but not sure how you'd resolve conflicts. If you wanna have that discussion open a separate issue.

It would certainly be more convenient if they could "overlap" like keymaps. I don't really grasp why they were originally implemented so that they couldn't. Keymaps can have conflicts and you just have to get them in the right order in the config file to do what you want. Or use variable switches like I've been doing. 

In the meantime, I've only done the non-terminal modmaps so far, but the strategy of making mutually-isolated conditions appears to be working, including undoing the "GTK3 fix" remapping whenever the "Mac Numpad" feature is engaged. Of course this requires a near-duplication of each modmap to maintain the basic remaps along the way. A bit cumbersome. 

Will open a separate issue. This one is effectively resolved.

**Comment by joshgoebel** [comment]
> Of course this requires a near-duplication of each modmap to maintain the basic remaps along the way. A bit cumbersome.

Because you're doing it the hard way. 😊 Gotta level up your Python and just generate the whole shebang and all variants programmatically.

**Comment by joshgoebel** [comment]
Did you join Exercism yet?

**Comment by RedBearAK** [comment]
> Did you join Exercism yet?

Not yet. It's not like I'm actually trying to be a programmer. LOL. 

> just generate the whole shebang and all variants programmatically

I'm sure that's possible, but you would have to take into account that Kinto has combined the four different keyboard types, and multi-language support, into the same two modmaps, and then behind the scenes a script activated by the Kinto GUI uses `sed` to just enable/disable the appropriate lines and restart the service. A lot would have to be changed not just in the config but in the Kinto installer and in the mechanism that Kinto uses for the GUI parts to allow the user to change keyboard types with a click from the tray icon. Not a project I really want to get into, since everything is technically working fine.

**Comment by joshgoebel** [comment]
> AttributeError: 'str' object has no attribute 'leds'

So you'd look for the one place device is still a string, and you'd find `wakeup_output`... hmmm.

**Comment by joshgoebel** [comment]
0bf2cdf

**Comment by joshgoebel** [comment]
>  It's not like I'm actually trying to be a programmer.

Oh but if you're writing a Keyzer config you are. 😃  One can be a programmer without being a professional.  And if you're going to dabble in Python it'd be easier if you learned a bit more.  But of course your call. 

>  A lot would have to be changed not just in the config but in the Kinto installer 

You might be right [about the installer], but I don't think so.  The whole kinto config could be simplified to use a SINGLE source of truth and then do all the settings programmatically...

So the only thing `sed` should do is uncomment a single line, something like:

```
system = "IBM"
```

That's probably more for @rbreaves to get around to figuring out one day though. :-)  Keymaps probably aren't perfectly composable yet, but I think they should be...

**Comment by RedBearAK** [comment]
> > AttributeError: 'str' object has no attribute 'leds'
> 
> So you'd look for the one place device is still a string, and you'd find `wakeup_output`... hmmm.

That’s funny, I was sure that function got called on every single startup, so I kind of dismissed it as the root of the issue. But of course that would cause this specific error.

**Comment by RedBearAK** [comment]
Alright I think I can confirm that not only did the fix make the error go away, but the new "in terminals" modmaps are actually working as I initially expected. Enabling the three different numpad states for all apps. Numlock ON, Numlock OFF, and "ignore Numlock and always be a numpad", with the GTK3 fix modmap enabled only in the "OFF" state when the nav key functions are available. Pretty neat. 

Thanks for the fix. 👍🏽

**Comment by joshgoebel** [comment]
> But of course that would cause this specific error.

It would as soon as you started adding conditionals that probed the status of the LEDS. :-)

**Comment by joshgoebel** [comment]
> but the new "in terminals" modmaps are actually working as I initially expected

This sounds like a big deal but I'm not sure what you're referring to. :)

**Comment by RedBearAK** [comment]
> It would as soon as you started adding conditionals that probed the status of the LEDS. :-)

Was it maybe working OK with the "GUI" modmaps because I'm always in a terminal when I start `keyszer` and then have to press at least one key (like Cmd+Tab) to get back to a non-terminal app to test the result of the modmap? So by the time I enter a GUI app and the modmap activates and tries to evaluate `numlock_on`, there's a real device available? 

I thought everything in the config file was evaluated on startup, so I'm still a little iffy on this scenario.

**Comment by joshgoebel** [comment]
Well, it's *parsed* on startup, but the conditional code isn't actually run until a key is pressed...Including the "fake" startup keys... so as soon as you starting calling numlock_on in your conditionals it all breaks.  Don't call it and it works great.

**Comment by RedBearAK** [comment]
> Well, it's parsed on startup (and a lot is run), but the conditional lambdas aren't actually run until a key is pressed

Gotcha.
