### ISSUE TITLE
 both of my keyboards get stuck.

### ISSUE THREAD

**Issue by joshgoebel** [joshgoebel/keyszer#87]
BTW, i guess there exists another bug, right? i describe it here, if is true, i will create a new issue.

```sh
 ╰─ $ keyszer --list-devices
keyszer v0.6.0
-----------------------------------------------------------------------------------
Device               Name                                Phys
-----------------------------------------------------------------------------------
/dev/input/event0    Lid Switch                          PNP0C0D/button/input0
/dev/input/event1    Power Button                        PNP0C0C/button/input0
/dev/input/event2    Sleep Button                        PNP0C0E/button/input0
/dev/input/event3    Power Button                        LNXPWRBN/button/input0
/dev/input/event4    AT Translated Set 2 keyboard        isa0060/serio0/input0
/dev/input/event5    MOSART Semi. wireless dongle        usb-0000:00:14.0-4/input0
/dev/input/event6    MOSART Semi. wireless dongle Mouse  usb-0000:00:14.0-4/input1
/dev/input/event7    MOSART Semi. wireless dongle Consumer Control
                                                         usb-0000:00:14.0-4/input1
/dev/input/event8    MOSART Semi. wireless dongle System Control
                                                         usb-0000:00:14.0-4/input1
/dev/input/event9    MOSART Semi. wireless dongle        usb-0000:00:14.0-4/input1
/dev/input/event10   MOSART Semi. wireless dongle        usb-0000:00:14.0-4/input1
/dev/input/event11   LG WMI hotkeys                      wmi/input0
/dev/input/event12   PC Speaker                          isa0061/input0
/dev/input/event13   LG Camera: LG Camera                usb-0000:00:14.0-6/button
/dev/input/event14   04CA00B1:00 04CA:00B1 Touchpad      i2c-04CA00B1:00
/dev/input/event15   04CA00B1:00 04CA:00B1 Mouse         i2c-04CA00B1:00
/dev/input/event16   Video Bus                           LNXVIDEO/video/input0
/dev/input/event17   HDA Intel PCH Mic                   ALSA
/dev/input/event18   HDA Intel PCH Headphone             ALSA
/dev/input/event19   HDA Intel PCH HDMI/DP,pcm=3         ALSA
/dev/input/event20   HDA Intel PCH HDMI/DP,pcm=7         ALSA
/dev/input/event21   HDA Intel PCH HDMI/DP,pcm=8         ALSA
/dev/input/event22   HDA Intel PCH HDMI/DP,pcm=9         ALSA
/dev/input/event23   HDA Intel PCH HDMI/DP,pcm=10        ALSA
/dev/input/event24   Keyszer (virtual) Keyboard          py-evdev-uinput

 ╰─ $ command ls -t /dev/input/by-path/*-kbd
/dev/input/by-path/pci-0000:00:14.0-usb-0:4:1.0-event-kbd  
/dev/input/by-path/platform-i8042-serio-0-event-kbd

 ╰─ $ readlink -e /dev/input/by-path/pci-0000:00:14.0-usb-0:4:1.0-event-kbd
/dev/input/event5

 ╰─ $ readlink -e /dev/input/by-path/platform-i8042-serio-0-event-kbd
/dev/input/event4

```

As you can see, i use two keyboard.

When i run keyszer, i use command like this:

```
keyszer -d /dev/input/event5 -c /home/zw963/utils/keyszer/bin/..//config_new.py

```

So, it should only map on /dev/input/event5, right?

But, the fact is, when the pressing issue happen, both of my keyboard all get stuck.

Following is output log when run from terminal

```sh
keyszer v0.6.0
(DD) CONFIG: /home/zw963/utils/keyszer/bin/..//config_new.py

(II) in LEFT_SHIFT (press)
(DD) on_key LEFT_SHIFT press
(DD) suspending keys [LShift<Key.LEFT_SHIFT>]

(II) in LEFT_SHIFT (release)
(DD) on_key LEFT_SHIFT release
(DD) resume because of mod release
(DD) resuming keys: [<Key.LEFT_SHIFT: 42>]
(OO) press LEFT_SHIFT
(OO) release LEFT_SHIFT
(+K) Grabbing MOSART Semi. wireless dongle (/dev/input/event5)
(--) Ready to process input.
```

_Originally posted by @zw963 in https://github.com/joshgoebel/keyszer/issues/81#issuecomment-1226751011_

**Comment by joshgoebel** [comment]
> So, it should only map on /dev/input/event5, right?

Yes, as it says it's doing: `(+K) Grabbing MOSART Semi. wireless dongle (/dev/input/event5)`

> But, the fact is, when the pressing issue happen, both of my keyboard all get stuck.

Well, if one keyboard is holding down a key, the other won't work properly - just give it a try yourself... press and hold the Ctrl or Super key on keyboard 1 (without Keyszer).... and try to do anything useful with keyboard 2 - you can't.  That's expected behavior.

**Comment by joshgoebel** [comment]
Also please make sure you're using 0.6.90 (just pushed) or newer....

**Comment by zw963** [comment]
Just double confirm i am describe my issue clearly.

```
keyszer -d /dev/input/event5 -c /home/zw963/utils/keyszer/bin/..//config_new.py
```

When keyszer works no issue, the key mapping only apply to  the keyboard which belongs to /dev/input/event5, this is what we expected.

But, when keyszer have issue(#81),  what i expected is,  the #81 issue only happen on /dev/input/event5, so, i can always stop keyszer service use my another keyboard, this is not possible, right?

**Comment by joshgoebel** [comment]
> so, i can always stop keyszer service use my another keyboard, this is not possible, right?

No, you can only "emergency stop" the service using a keyboard it's "listening" to.  But again, even if Keyszer is very confused I've *never* seen emergency stop or diag stop working... those keys should always work fine.

**Comment by zw963** [comment]
> > so, i can always stop keyszer service use my another keyboard, this is not possible, right?
> 
> No, you can only "emergency stop" the service using a keyboard it's "listening" to. But again, even if Keyszer is very confused I've _never_ seen emergency stop or diag stop working... those keys should always work fine.

No, what i sand `stop keyszer` is, when i listening keyboard on `/dev/input/event5` only, can i stop the keyszer service on my another not listened keyboard, e.g. /dev/input/event6,  or, another word, when event5 Ctrl is keep pressed by keyszer unexpectedly, ctrl is not work for event6, right?

**Comment by joshgoebel** [comment]
I already addressed this.

> if one keyboard is holding down a key, the other can't work properly

**Comment by zw963** [comment]
> if one keyboard is holding down a key, the other can't work properly

I use newest master, when ctrl is keeping pressing, both of keyboard can not work correct even i bind to only one of them?

**Comment by joshgoebel** [comment]
**For the third time, yes...** this has nothing to do with Keyszer.  Holding a key down forever tends to break things badly.

**Comment by joshgoebel** [comment]
Closing this as wontfix/"expected behavior"... we need to focus on the other thread of finding out why the keys are getting stuck once in a while.
